"use client";

/* eslint-disable react-hooks/exhaustive-deps, @next/next/no-img-element */
import {useEffect,useRef,useState,type CSSProperties,type FormEvent,type RefObject} from "react";
import {ChevronDown,Download,ExternalLink,FileImage,FileSpreadsheet,FileText,FileType2,Maximize2,Minus,Plus,RefreshCw,Upload,X,ZoomIn} from "lucide-react";
import type {V2Project} from "./project-workspaces";
import {useAiContextSelection} from "./ai-context-selection";

type ModuleTask={id:string;wbsCode:string;kind:string;name:string};
type Deliverable={id:string;projectId:string;projectCode:string;projectName:string;taskId?:string;taskCode?:string;taskName?:string;name:string;type?:string;required?:boolean|number;status:string;version?:string;source:string;revisionCount:number;documentKind?:"document"|"drawing";drawingCode?:string;drawingType?:string;internalDrawingNumber?:string;customerDrawingNumber?:string;ownerDepartment?:string;ownerUserId?:string;workflowId?:string;workflowNumber?:string;workflowTitle?:string;approvedAt?:number;finalApprover?:string};
type DeliverableVersion={id:string;deliverableId:string;taskId?:string;revision:number;fileName:string;fileSize:number;contentType?:string;note?:string;previewFileKey?:string;conversionStatus?:string;conversionError?:string;convertedAt?:number;createdAt:number;createdBy?:string};
type PreviewTab={id:string;projectId:string;deliverableId:string;title:string;versionId:string};
type ListResponse={deliverables?:Deliverable[];versions?:DeliverableVersion[];error?:string};
type LibraryMode="document"|"drawing";

const bytes=(value:number)=>value>=1024*1024?`${(value/1024/1024).toFixed(1)} MB`:value>=1024?`${Math.round(value/1024)} KB`:`${value||0} B`;
const iconFor=(name:string)=>/\.(png|jpe?g|gif|webp|svg)$/i.test(name)?FileImage:/\.xlsx?$/i.test(name)?FileSpreadsheet:/\.(docx?|pdf|pptx?)$/i.test(name)?FileType2:FileText;
const isDrawing=(item:Deliverable)=>item.documentKind==="drawing";
const reviewStatusLabel=(status:string)=>status==="approved"?"승인":status==="rejected"?"반려":"등록 완료";

export function PreviewDocumentsWorkspace({project,projects,tasks,initialDeliverableId,onInitialOpened,onOpenTask,onAddDeliverable,libraryMode="document",onLibraryModeChange,onOpenDetail,refreshVersion=0}:{project:V2Project|null;projects:V2Project[];tasks:ModuleTask[];initialDeliverableId?:string;onInitialOpened?:()=>void;onOpenTask:(projectId:string,taskId:string)=>void;onAddDeliverable:(projectId:string,taskId:string,mode?:"deliverable"|"drawing",deliverableId?:string)=>void;libraryMode?:LibraryMode;onLibraryModeChange?:(mode:LibraryMode)=>void;onOpenDetail?:(deliverableId:string)=>void;refreshVersion?:number}){
  const selection=useAiContextSelection("문서 · 산출물");
  const [items,setItems]=useState<Deliverable[]>([]),[versions,setVersions]=useState<DeliverableVersion[]>([]);
  const [loading,setLoading]=useState(false),[notice,setNotice]=useState("");
  const [tabs,setTabs]=useState<PreviewTab[]>([]),[activeTab,setActiveTab]=useState("library"),[tabsReady,setTabsReady]=useState(false),[dialog,setDialog]=useState(false),[dialogTasks,setDialogTasks]=useState<ModuleTask[]>(tasks),[saving,setSaving]=useState(false);
  const fileRef=useRef<HTMLInputElement|null>(null),viewerRef=useRef<HTMLDivElement|null>(null);
  const [form,setForm]=useState({projectId:"",taskId:"",deliverableId:"",name:"",category:"",note:""});

  const latestFor=(deliverableId:string)=>versions.find(version=>version.deliverableId===deliverableId);
  const load=async(signal?:AbortSignal)=>{setLoading(true);try{const response=await fetch(`/api/deliverables?documentKind=${libraryMode}&registration=completed`,{cache:"no-store",signal});const data=await response.json() as ListResponse;if(!response.ok)throw new Error(data.error||"산출물을 불러오지 못했습니다.");const nextVersions=data.versions??[];const registered=(data.deliverables??[]).filter(item=>nextVersions.some(version=>version.deliverableId===item.id));registered.sort((a,b)=>(nextVersions.find(version=>version.deliverableId===b.id)?.createdAt??0)-(nextVersions.find(version=>version.deliverableId===a.id)?.createdAt??0));setItems(registered);setVersions(nextVersions);setNotice("")}catch(reason){if(!(reason instanceof DOMException&&reason.name==="AbortError")){setItems([]);setVersions([]);setNotice(reason instanceof Error?reason.message:"산출물을 불러오지 못했습니다.")}}finally{if(!signal?.aborted)setLoading(false)}};
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[libraryMode,refreshVersion]);

  const loadVersionHistory=async(deliverableId:string)=>{const response=await fetch(`/api/deliverables?deliverableId=${encodeURIComponent(deliverableId)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Revision 이력을 불러오지 못했습니다.");const history=(data.versions??[]) as DeliverableVersion[];if(data.deliverable)setItems(current=>current.map(item=>item.id===deliverableId?{...item,...data.deliverable}:item));setVersions(current=>[...current.filter(version=>version.deliverableId!==deliverableId),...history]);return history};
  const openPreview=(item:Deliverable,version=latestFor(item.id))=>{if(!version){setNotice("미리볼 Revision이 없습니다.");return}const id=`preview:${item.id}`;setTabs(current=>current.some(tab=>tab.id===id)?current.map(tab=>tab.id===id?{...tab,versionId:version.id,title:item.name,projectId:item.projectId}:tab):[...current,{id,projectId:item.projectId,deliverableId:item.id,title:item.name,versionId:version.id}]);setActiveTab(id);void loadVersionHistory(item.id).catch(reason=>setNotice(reason instanceof Error?reason.message:"Revision 이력을 불러오지 못했습니다."))};

  useEffect(()=>{const controller=new AbortController();fetch("/api/state?key=v2-document-preview-tabs",{cache:"no-store",signal:controller.signal}).then(response=>response.ok?response.json():Promise.reject()).then(({value}:{value?:{tabs?:PreviewTab[];active?:string}})=>{if(Array.isArray(value?.tabs))setTabs(value.tabs);if(value?.active)setActiveTab(value.active)}).catch(()=>undefined).finally(()=>{if(!controller.signal.aborted)setTabsReady(true)});return()=>controller.abort()},[]);
  useEffect(()=>{if(!tabsReady)return;const timer=window.setTimeout(()=>{void fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({key:"v2-document-preview-tabs",value:{tabs,active:activeTab}})})},220);return()=>window.clearTimeout(timer)},[tabs,activeTab,tabsReady]);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<{deliverableId?:string;versionId?:string}>).detail,item=items.find(row=>row.id===detail?.deliverableId);if(!item)return;const local=detail?.versionId?versions.find(version=>version.id===detail.versionId):latestFor(item.id);if(local){openPreview(item,local);return}void loadVersionHistory(item.id).then(history=>openPreview(item,detail?.versionId?history.find(version=>version.id===detail.versionId):history[0])).catch(()=>undefined)};window.addEventListener("v2-open-document-preview",handler);return()=>window.removeEventListener("v2-open-document-preview",handler)},[items,versions]);
  useEffect(()=>{if(!initialDeliverableId||!items.length)return;const item=items.find(row=>row.id===initialDeliverableId);if(!item)return;const latest=latestFor(item.id);if(latest)openPreview(item,latest);else void loadVersionHistory(item.id).then(history=>openPreview(item,history[0]));onInitialOpened?.()},[initialDeliverableId,items,versions]);
  const closeTab=(id:string)=>{setTabs(current=>current.filter(tab=>tab.id!==id));if(activeTab===id)setActiveTab("library")};
  const updateTabVersion=(id:string,versionId:string)=>{const target=tabs.find(tab=>tab.id===id);setTabs(current=>current.map(tab=>tab.id===id?{...tab,versionId}:tab));if(target)void loadVersionHistory(target.deliverableId).catch(reason=>setNotice(reason instanceof Error?reason.message:"Revision 이력을 불러오지 못했습니다."))};
  const registrationProject=project||projects[0]||null;

  const getTasks=async(target:V2Project)=>{if(target.id===project?.id&&tasks.length)return tasks;const response=await fetch(`/api/projects/${target.id}/wbs`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Task를 불러오지 못했습니다.");return (data.tasks??[]) as ModuleTask[]};
  const openDrawingPanel=async(item?:Deliverable)=>{const target=item?projects.find(candidate=>candidate.id===item.projectId)||registrationProject:registrationProject;if(!target){setNotice("등록할 프로젝트를 선택해 주세요.");return}try{const available=await getTasks(target),taskId=item?.taskId||available.find(row=>row.kind==="task")?.id;if(!taskId){setNotice("도면을 연결할 Task가 없습니다.");return}setNotice("");onAddDeliverable(target.id,taskId,"drawing",item?.id)}catch(reason){setNotice(reason instanceof Error?reason.message:"Task를 불러오지 못했습니다.")}};
  const openDialog=async(item?:Deliverable)=>{if(item&&isDrawing(item)){void openDrawingPanel(item);return}const target=item?projects.find(candidate=>candidate.id===item.projectId)||registrationProject:registrationProject;if(!target){setNotice("등록할 프로젝트를 선택해 주세요.");return}try{const available=await getTasks(target);setDialogTasks(available);setForm({projectId:target.id,taskId:item?.taskId||available.find(task=>task.kind==="task")?.id||"",deliverableId:item?.id||"",name:item?.source==="ad_hoc"?item.name:"",category:item?.type||"",note:""});setDialog(true);setNotice("")}catch(reason){setNotice(reason instanceof Error?reason.message:"Task를 불러오지 못했습니다.")}};
  const openAddPanel=async()=>{const target=registrationProject;if(!target){setNotice("등록할 프로젝트를 선택해 주세요.");return}try{const available=await getTasks(target),task=available.find(row=>row.kind==="task");if(!task){setNotice("산출물을 연결할 Task가 없습니다.");return}onAddDeliverable(target.id,task.id)}catch(reason){setNotice(reason instanceof Error?reason.message:"Task를 불러오지 못했습니다.")}};
  const submit=async(event?:FormEvent)=>{event?.preventDefault();const targetProjectId=form.projectId||registrationProject?.id,file=fileRef.current?.files?.[0];if(!targetProjectId||!file){setNotice("등록할 프로젝트와 파일을 선택해 주세요.");return}setSaving(true);const data=new FormData();Object.entries(form).forEach(([key,value])=>data.set(key,value));data.set("file",file);try{const response=await fetch(`/api/projects/${targetProjectId}/deliverables`,{method:"POST",body:data});const result=await response.json();if(!response.ok)throw new Error(result.error||"파일을 등록하지 못했습니다.");setDialog(false);setNotice(`${result.version||"새 Revision"}으로 등록했습니다.`);await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"파일을 등록하지 못했습니다.")}finally{setSaving(false)}};

  const active=tabs.find(tab=>tab.id===activeTab);
  const contextFor=(item:Deliverable)=>{const latest=latestFor(item.id);return {id:item.id,kind:"문서",title:item.name,meta:`${item.projectCode||"프로젝트 미지정"} · ${item.taskCode||"WBS 미지정"} · ${latest?`Rev.${latest.revision}`:"Revision 없음"}`,fileName:latest?.fileName,revision:latest?.revision,fileAttached:Boolean(latest)}};

  return <section className="wv2-module wv2-document-workspace"><header className="wv2-module-head"><div><small>DOCUMENT · DELIVERABLE · PREVIEW</small><h1>문서 · 산출물</h1><p>시스템에 실제 등록된 문서와 도면을 확인합니다.</p></div><div className="wv2-module-head-actions"><button disabled={!registrationProject&&!projects.length} onClick={()=>openDrawingPanel()}><FileText size={18}/>도면 등록</button><button className="primary" disabled={!registrationProject} onClick={()=>void openAddPanel()}><Upload size={18}/>추가 산출물 등록</button></div></header>
    <nav className="wv2-preview-tabs"><button className={activeTab==="library"&&libraryMode==="document"?"active":""} onClick={()=>{setActiveTab("library");onLibraryModeChange?.("document")}}><FileText size={18}/>문서 라이브러리</button><button className={activeTab==="library"&&libraryMode==="drawing"?"active":""} onClick={()=>{setActiveTab("library");onLibraryModeChange?.("drawing")}}><FileText size={18}/>도면 라이브러리</button>{tabs.map(tab=><button key={tab.id} className={activeTab===tab.id?"active":""} onClick={()=>setActiveTab(tab.id)}><span>{tab.title}</span><X size={18} onClick={event=>{event.stopPropagation();closeTab(tab.id)}}/></button>)}<button className="add" onClick={()=>setActiveTab("library")}><Plus size={18}/></button></nav>
    {notice&&<p className="wv2-module-notice">{notice}</p>}
    {active?<DocumentPreview projectId={active.projectId} tab={active} item={items.find(item=>item.id===active.deliverableId)} versions={versions.filter(version=>version.deliverableId===active.deliverableId)} onVersion={versionId=>updateTabVersion(active.id,versionId)} onRegisterRevision={item=>void openDialog(item)} viewerRef={viewerRef}/>:loading&&!items.length?<div className="wv2-preview-empty"><RefreshCw size={25}/><b>등록 문서를 불러오는 중…</b></div>:<div className="wv2-document-table wv2-preview-document-table"><header><span className="select"><input type="checkbox" checked={Boolean(items.length)&&items.every(item=>selection.has(contextFor(item)))} onChange={()=>items.every(item=>selection.has(contextFor(item)))?selection.clear():items.forEach(item=>{if(!selection.has(contextFor(item)))selection.toggle(contextFor(item))})}/></span><span>산출물</span><span>프로젝트 · WBS</span><span>구분</span><span>Revision</span><span>상태</span><span/></header>{items.map(item=>{const latest=latestFor(item.id),Icon=latest?iconFor(latest.fileName):FileText,drawing=isDrawing(item);return <article key={item.id}><span className="select"><input type="checkbox" checked={selection.has(contextFor(item))} onChange={()=>selection.toggle(contextFor(item))}/></span><button className="name" onClick={()=>onOpenDetail?onOpenDetail(item.id):latest&&openPreview(item)}><Icon size={18}/><span><b>{item.name}</b><small>{drawing?`${item.drawingCode||"도면코드"} · ${item.drawingType||"도면"}`:item.type||"일반문서"}</small></span></button><button className="wv2-document-task" onClick={()=>item.taskId&&onOpenTask(item.projectId,item.taskId)}><b>{item.projectCode||"프로젝트 미지정"} · {item.projectName||""}</b><small>{item.taskCode?`${item.taskCode} ${item.taskName||""}`:"WBS 미지정"}</small></button><em>{drawing?"도면":"문서"}</em><button className="wv2-revision-link" disabled={!latest} onClick={()=>latest&&openPreview(item)}>{latest?<><b>Rev.{String(latest.revision).padStart(2,"0")}</b><small>{latest.fileName} · {bytes(latest.fileSize)}</small></>:"—"}</button><span className="wv2-document-status"><i className="submitted">{reviewStatusLabel(item.status)}</i></span><button disabled={!latest} onClick={()=>latest&&openPreview(item)}>미리보기</button></article>})}</div>}
    {dialog&&<div className="wv2-module-dialog-backdrop"><form className="wv2-module-dialog" onSubmit={submit}><header><div><small>DELIVERABLE UPLOAD</small><h2>{form.deliverableId?"산출물 Revision 등록":"추가 산출물 등록"}</h2></div><button type="button" onClick={()=>setDialog(false)}>×</button></header><label><span>연결 Task *</span><select required value={form.taskId} onChange={event=>setForm(current=>({...current,taskId:event.target.value}))}><option value="">선택</option>{dialogTasks.filter(task=>task.kind==="task").map(task=><option value={task.id} key={task.id}>{task.wbsCode} {task.name}</option>)}</select></label>{form.deliverableId?<label><span>산출물</span><select value={form.deliverableId} onChange={event=>setForm(current=>({...current,deliverableId:event.target.value}))}>{items.filter(item=>!isDrawing(item)).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>:<><label><span>산출물명</span><input value={form.name} onChange={event=>setForm(current=>({...current,name:event.target.value}))}/></label><label><span>문서 카테고리</span><input value={form.category} onChange={event=>setForm(current=>({...current,category:event.target.value}))}/></label></>}<label><span>파일</span><input ref={fileRef} type="file" required/></label><label><span>등록 메모</span><textarea rows={3} value={form.note} onChange={event=>setForm(current=>({...current,note:event.target.value}))}/></label><footer><button type="button" onClick={()=>setDialog(false)}>취소</button><button className="primary" disabled={saving}>{saving?"등록 중…":"파일 등록"}</button></footer></form></div>}
  </section>;
}

function DocumentPreview({projectId,tab,item,versions,onVersion,onRegisterRevision,viewerRef}:{projectId:string;tab:PreviewTab;item?:Deliverable;versions:DeliverableVersion[];onVersion:(id:string)=>void;onRegisterRevision:(item:Deliverable)=>void;viewerRef:RefObject<HTMLDivElement|null>}){
  const version=versions.find(candidate=>candidate.id===tab.versionId)??versions[0];const [text,setText]=useState("");const [error,setError]=useState<{message:string;downloadAvailable:boolean}|null>(null);const [loading,setLoading]=useState(true);const [zoom,setZoom]=useState(100);const [fit,setFit]=useState(true);const [reloadKey,setReloadKey]=useState(0);const [conversionStatus,setConversionStatus]=useState(version?.conversionStatus||"");const [conversionError,setConversionError]=useState(version?.conversionError||"");const [conversionSaving,setConversionSaving]=useState(false);useEffect(()=>{setConversionStatus(version?.conversionStatus||"");setConversionError(version?.conversionError||"")},[version?.id,version?.conversionStatus,version?.conversionError]);
  const url=version?`/api/projects/${projectId}/deliverables?versionId=${encodeURIComponent(version.id)}&preview=1`:"";const lower=version?.fileName.toLowerCase()||"";const kind=version?.contentType?.startsWith("image/")||/\.(png|jpe?g|gif|webp|svg)$/i.test(lower)?"image":version?.contentType==="application/pdf"||lower.endsWith(".pdf")?"pdf":lower.endsWith(".dwg")?"dwg":/\.(docx|pptx|xlsx|txt|csv|json|xml|md)$/i.test(lower)||version?.contentType?.startsWith("text/")?"text":"unsupported";
  useEffect(()=>{setText("");setError(null);setZoom(100);setFit(true);if(!version){setLoading(false);return}if(kind!=="text"){setLoading(false);return}setLoading(true);fetch(url,{cache:"no-store"}).then(async response=>{const data=await response.json().catch(()=>null) as {text?:string;error?:string;downloadAvailable?:boolean}|null;if(!response.ok)throw {message:data?.error||"문서 미리보기를 불러오지 못했습니다.",downloadAvailable:Boolean(data?.downloadAvailable)};setText(data?.text||"")}).catch(reason=>setError({message:typeof reason?.message==="string"?reason.message:"문서 미리보기를 불러오지 못했습니다.",downloadAvailable:Boolean(reason?.downloadAvailable)})).finally(()=>setLoading(false))},[version?.id,reloadKey]);
  const download=version?`/api/projects/${projectId}/deliverables?versionId=${encodeURIComponent(version.id)}`:"";
  const retryConversion=async()=>{if(!version)return;setConversionSaving(true);setConversionError("");try{const response=await fetch(`/api/projects/${projectId}/deliverables`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"retry-conversion",versionId:version.id})});const result=await response.json();if(!response.ok)throw new Error(result.error||"DWG 변환에 실패했습니다.");setConversionStatus(result.status||"converted");if(result.error)setConversionError(result.error);setReloadKey(value=>value+1)}catch(reason){setConversionStatus("failed");setConversionError(reason instanceof Error?reason.message:"DWG 변환에 실패했습니다.")}finally{setConversionSaving(false)}};
  const textStyle={"--v2-preview-text-size":`${Math.max(12,Math.round(zoom*0.14))}px`} as CSSProperties;
  const approvalMeta=item?.workflowNumber?`승인 완료 · ${item.workflowNumber} · ${item.finalApprover||"최종 승인자"}${item.approvedAt?` · ${new Date(Number(item.approvedAt)*1000).toLocaleDateString("ko-KR")}`:""}`:"";
  return <div className="wv2-document-preview" ref={viewerRef}><header><div><span><b>{item?.drawingCode?`${item.drawingCode} · ${item.name}`:item?.name||tab.title}</b><small>{version?.fileName||"Revision 없음"}{version?` · ${bytes(version.fileSize)}`:""}</small>{approvalMeta&&<em>{approvalMeta}</em>}</span></div><div className="wv2-preview-actions"><label>Revision <select value={version?.id||""} onChange={event=>onVersion(event.target.value)}>{versions.map(candidate=><option key={candidate.id} value={candidate.id}>Rev.{String(candidate.revision).padStart(2,"0")} · {candidate.fileName}</option>)}</select><ChevronDown size={18}/></label><button title="축소" onClick={()=>{setFit(false);setZoom(value=>Math.max(50,(fit?100:value)-10))}}><Minus size={18}/></button><button className="wv2-preview-zoom-label" title="화면 맞춤" onClick={()=>{setFit(true);setZoom(100)}}>{fit?"맞춤":`${zoom}%`}</button><button title="확대" onClick={()=>{setFit(false);setZoom(value=>Math.min(200,(fit?100:value)+10))}}><ZoomIn size={18}/></button><button title="전체 화면" onClick={()=>viewerRef.current?.requestFullscreen()}><Maximize2 size={18}/></button>{item&&<button onClick={()=>onRegisterRevision(item)}><Upload size={18}/>{isDrawing(item)?"새 Rev 등록":"Revision 등록"}</button>}<a href={download} download><Download size={18}/>다운로드</a></div></header><main>{loading?<div className="wv2-preview-empty"><RefreshCw className="wv2-spin" size={24}/><b>문서를 변환하는 중…</b></div>:error?<div className="wv2-preview-empty wv2-preview-error"><FileText size={24}/><b>{error.message}</b><span>{error.downloadAvailable?"원본 파일은 정상이며 다운로드하여 확인할 수 있습니다.":"파일 등록 상태를 확인한 뒤 다시 시도해 주세요."}</span><div><button onClick={()=>setReloadKey(value=>value+1)}><RefreshCw size={18}/>다시 시도</button>{error.downloadAvailable&&<a href={download} download><Download size={18}/>원본 다운로드</a>}</div></div>:kind==="image"?<div className={`wv2-image-preview ${fit?"fit":"zoomed"}`}><img src={url} alt={version?.fileName} style={fit?undefined:{width:`${zoom}%`}}/></div>:kind==="pdf"?<iframe src={url} title={version?.fileName}/>:kind==="text"?<pre style={textStyle}>{text}</pre>:kind==="dwg"?(conversionStatus==="converted"?<iframe src={`${url}&reload=${reloadKey}`} title={`${version?.fileName} PDF 변환 미리보기`}/>:<div className="wv2-preview-empty"><RefreshCw size={26}/><b>{conversionStatus==="converting"?"DWG를 PDF로 변환하는 중입니다.":conversionStatus==="unconfigured"?"DWG 변환 서버 연결이 필요합니다.":conversionStatus==="failed"?"DWG 변환에 실패했습니다.":"DWG PDF 미리보기를 준비 중입니다."}</b><span>{conversionError||"원본 DWG는 정상 보관되며 변환 후 브라우저 미리보기가 제공됩니다."}</span><div><button disabled={conversionSaving} onClick={retryConversion}><RefreshCw size={18}/>{conversionSaving?"변환 요청 중…":"변환 다시 시도"}</button><a href={download} download><Download size={18}/>원본 다운로드</a></div></div>):<div className="wv2-preview-empty"><ExternalLink size={26}/><b>이 형식은 브라우저 내 미리보기를 지원하지 않습니다.</b><span>다운로드하여 원본 프로그램에서 확인해 주세요.</span><a href={download}>파일 열기</a></div>}</main></div>;
}
