"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useEffect,useMemo,useRef,useState} from "react";
import {Check,FileText,Trash2,Upload,X} from "lucide-react";
import "./workflow-document.css";

type Project={id:string;code:string;name:string};
type Step={name:string;actionType:string;roleCode?:string;assignmentRule?:string;dueDays?:number;commentRequired?:boolean;attachmentRequired?:boolean};
type Member={userId:string;name:string;email?:string;projectRole:string};
type DirectoryUser={userId:string;name:string;email?:string;organizationPath?:string;roleNames?:string};
type DrawingOption={id:string;projectId:string;projectCode:string;projectName:string;name:string;drawingCode?:string|null;drawingType?:string|null;taskId?:string|null;taskCode?:string|null;taskName?:string|null};
type CommonCodeOption={code:string;label:string;groupCode:string;enabled?:boolean|number};
type PartOption={id:string;partNumber:string;name:string;partType:string;spec?:string|null;unit:string;revision:string;status:string};

const actionLabels:Record<string,string>={WRITE:"작성",PROCESS:"처리",REVIEW:"검토",AGREEMENT:"합의",APPROVAL:"승인",REFERENCE:"참조"};
const json=async(response:Response)=>{const text=await response.text();let data:any={};if(text){try{data=JSON.parse(text)}catch{data={error:text}}}if(!response.ok)throw new Error(data.error||`요청을 처리하지 못했습니다. (${response.status})`);return data};
const automaticAssignees=(steps:Step[],members:Member[])=>{const result:Record<string,string>={};steps.forEach((step,index)=>{if(step.assignmentRule==="requester")return;const wanted=step.assignmentRule==="project_pm"?"PM":step.assignmentRule==="project_pl"?"PL":step.roleCode;const match=members.find(member=>wanted&&member.projectRole.toUpperCase()===wanted.toUpperCase());if(match)result[String(index)]=match.userId});return result};

function OrganizationAssigneeSelect({users,value,onChange,required=true}:{users:DirectoryUser[];value:string;onChange:(value:string)=>void;required?:boolean}){
  const groups=users.reduce<Record<string,DirectoryUser[]>>((result,user)=>{const key=user.organizationPath||"소속 미지정";(result[key]??=[]).push(user);return result},{});
  return <select aria-label="전체 조직 담당자" className={!value&&required?"required":""} value={value} onChange={event=>onChange(event.target.value)}><option value="">{required?"담당자 지정 필요":"담당자 선택(선택)"}</option>{Object.entries(groups).map(([organization,items])=><optgroup key={organization} label={organization}>{items.map(user=><option key={user.userId} value={user.userId}>{user.name}{user.email?` · ${user.email}`:""}{user.roleNames?` · ${user.roleNames}`:""}</option>)}</optgroup>)}</select>;
}

export function SourceCreateWorkspace({kind,projects,initialProjectId,editId,onCancel,onCreated}:{kind:"ECR"|"QUALITY";projects:Project[];initialProjectId:string;editId?:string;onCancel:()=>void;onCreated:(workflowId?:string)=>void}){
  const ecr=kind==="ECR",endpoint=ecr?"/api/ecr":"/api/quality",fileInput=useRef<HTMLInputElement>(null);
  const [form,setForm]=useState<any>({projectId:initialProjectId,partId:"",drawingId:"",title:"",changeType:"",priority:"normal",severity:"medium",occurredOn:new Date().toISOString().slice(0,10),dueDate:"",beforeContent:"",afterContent:"",reason:"",impactContent:"",issueType:"",description:"",rootCause:"",correctiveAction:"",effectivenessCheck:""});
  const [parts,setParts]=useState<PartOption[]>([]),[partSearch,setPartSearch]=useState(""),[partLoading,setPartLoading]=useState(false);
  const [drawings,setDrawings]=useState<DrawingOption[]>([]),[drawingSearch,setDrawingSearch]=useState(""),[drawingLoading,setDrawingLoading]=useState(false);
  const [steps,setSteps]=useState<Step[]>([]),[users,setUsers]=useState<DirectoryUser[]>([]),[assignees,setAssignees]=useState<Record<string,string>>({});
  const [attachments,setAttachments]=useState<any[]>([]),[removeAttachmentIds,setRemoveAttachmentIds]=useState<string[]>([]),[files,setFiles]=useState<File[]>([]),[dragging,setDragging]=useState(false);
  const [optionsLoading,setOptionsLoading]=useState(false),[loadingEdit,setLoadingEdit]=useState(Boolean(editId)),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const [qualityIssueTypes,setQualityIssueTypes]=useState<CommonCodeOption[]>([]),[designChangeTypes,setDesignChangeTypes]=useState<CommonCodeOption[]>([]);

  useEffect(()=>{const controller=new AbortController();fetch("/api/system/master-data",{cache:"no-store",signal:controller.signal}).then(json).then(data=>{const codes=(data.codes??[]) as CommonCodeOption[];setQualityIssueTypes(codes.filter(item=>item.groupCode==="QUALITY_ISSUE_TYPE"&&item.enabled!==false&&item.enabled!==0));setDesignChangeTypes(codes.filter(item=>item.groupCode==="DESIGN_CHANGE_TYPE"&&item.enabled!==false&&item.enabled!==0))}).catch(()=>{});return()=>controller.abort()},[]);

  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setPartLoading(true);const params=new URLSearchParams();if(partSearch.trim())params.set("q",partSearch.trim());fetch(`/api/workflows/part-options?${params}`,{cache:"no-store",signal:controller.signal}).then(json).then(data=>setParts(data.parts??[])).catch(reason=>{if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"PART를 불러오지 못했습니다.")}).finally(()=>setPartLoading(false))},180);return()=>{clearTimeout(timer);controller.abort()}},[partSearch]);

  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setDrawingLoading(true);const params=new URLSearchParams();if(drawingSearch.trim())params.set("q",drawingSearch.trim());fetch(`/api/workflows/drawing-options?${params}`,{cache:"no-store",signal:controller.signal}).then(json).then(data=>setDrawings(data.drawings??[])).catch(reason=>{if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"도면을 불러오지 못했습니다.")}).finally(()=>setDrawingLoading(false))},180);return()=>{clearTimeout(timer);controller.abort()}},[drawingSearch]);

  useEffect(()=>{if(!editId)return;setLoadingEdit(true);fetch(`${endpoint}?id=${editId}`,{cache:"no-store"}).then(json).then(async data=>{const item=data.item;setForm((current:any)=>({...current,...item,partId:item.partId||data.part?.id||"",drawingId:item.drawingId||data.drawing?.id||""}));setAttachments(data.attachments??[]);if(item.partId||data.part?.id)setPartSearch(item.partNumber||data.part?.partNumber||"");if(item.drawingId||data.drawing?.id)setDrawingSearch(item.drawingCode||data.drawing?.drawingCode||data.drawing?.id||"");if(item.workflowId){const detail=await fetch(`/api/workflows/${item.workflowId}`,{cache:"no-store"}).then(json);if(detail.workflow.status!=="draft")throw new Error("임시저장 상태에서만 수정할 수 있습니다.");setSteps((detail.steps??[]).map((step:any)=>({name:step.name||step.step_name,actionType:step.action_type,roleCode:step.role_code,assignmentRule:step.assignment_rule,dueDays:step.due_days,commentRequired:Boolean(step.comment_required),attachmentRequired:Boolean(step.attachment_required)})));setAssignees(Object.fromEntries((detail.steps??[]).filter((step:any)=>step.assignee_user_id).map((step:any)=>[String(step.step_order),step.assignee_user_id])))}}).catch(reason=>setError(reason instanceof Error?reason.message:"임시저장 정보를 불러오지 못했습니다.")).finally(()=>setLoadingEdit(false))},[editId,endpoint]);

  useEffect(()=>{if(!form.projectId){setSteps([]);setUsers([]);setAssignees({});return}setOptionsLoading(true);const templateCode=ecr?"EC_ACTION":"QUALITY_ACTION";fetch(`/api/workflows/options?projectId=${encodeURIComponent(form.projectId)}&templateCode=${templateCode}`,{cache:"no-store"}).then(json).then(data=>{setSteps(current=>editId&&current.length?current:data.steps??[]);setUsers(data.users??[]);setAssignees(current=>editId&&Object.keys(current).length?current:automaticAssignees(data.steps??[],data.members??[]))}).catch(reason=>setError(reason instanceof Error?reason.message:"담당자 정보를 불러오지 못했습니다.")).finally(()=>setOptionsLoading(false))},[ecr,form.projectId,editId]);

  const partLabel=(item:PartOption)=>`${item.partNumber} · ${item.name} · Rev.${item.revision}`;
  const selectedPart=parts.find(item=>item.id===form.partId);
  const visibleParts=useMemo(()=>parts.slice(0,80),[parts]);
  const choosePart=(value:string)=>{setPartSearch(value);const selected=parts.find(item=>partLabel(item)===value||item.id===value||item.partNumber===value||`${item.partNumber} · ${item.name}`===value);setForm((current:any)=>({...current,partId:selected?.id||""}))};
  const selectedDrawing=drawings.find(item=>item.id===form.drawingId);
  const chooseDrawing=(value:string)=>{setDrawingSearch(value);const selected=drawings.find(item=>drawingLabel(item)===value||item.id===value||item.drawingCode===value);setForm((current:any)=>({...current,drawingId:selected?.id||"",projectId:current.projectId||selected?.projectId||""}))};
  const drawingProjectMismatch=Boolean(selectedDrawing&&form.projectId&&selectedDrawing.projectId!==form.projectId);
  const missingAssignee=steps.some((step,index)=>index>0&&step.actionType!=="REFERENCE"&&!assignees[String(index)]);
  const addFiles=(incoming:FileList|File[])=>setFiles(current=>[...current,...Array.from(incoming).filter(file=>!current.some(item=>item.name===file.name&&item.size===file.size))]);
  const save=async()=>{setSaving(true);setError("");try{const body=new FormData();body.set("payload",JSON.stringify({...form,id:editId,assignees,removeAttachmentIds}));files.forEach(file=>body.append("files",file));const data=await fetch(endpoint,{method:editId?"PATCH":"POST",body}).then(json);onCreated(data.workflowId||data.workflow?.id)}catch(reason){setError(reason instanceof Error?reason.message:"저장하지 못했습니다.")}finally{setSaving(false)}};
  const activeAttachments=attachments.filter(item=>!removeAttachmentIds.includes(item.id));

  return <section className="wv2-workflow-create source wv2-central-create-workspace"><header><div><small>{editId?(ecr?"EDIT DRAFT ENGINEERING CHANGE":"EDIT DRAFT QUALITY CASE"):(ecr?"NEW ENGINEERING CHANGE":"NEW QUALITY CASE")}</small><h1>{editId?(ecr?"설계변경 수정":"품질문제 수정"):(ecr?"새 설계변경":"새 품질문제")}</h1><p>{editId?"임시저장된 업무 정보와 관련 대상을 수정합니다.":"관련 PART와 도면은 필요할 때 각각 독립적으로 연결할 수 있습니다."}</p></div><div className="wv2-central-create-actions"><button onClick={onCancel}>취소</button><button className="primary" disabled={saving||loadingEdit||optionsLoading||!form.projectId||!form.title.trim()||!steps.length||missingAssignee} onClick={save}><Check size={18}/>{saving?"저장 중…":editId?"변경사항 저장":"등록"}</button><button aria-label="작성 탭 닫기" onClick={onCancel}><X size={18}/></button></div></header>
  <main><div className="wv2-source-create-layout"><div className="wv2-workflow-form">
    <div className="two"><label><span>프로젝트 *</span><select disabled={Boolean(editId)} value={form.projectId} onChange={event=>setForm({...form,projectId:event.target.value})}><option value="">선택</option>{projects.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label><span>관련 PART</span><input list={`${kind.toLowerCase()}-part-options`} value={partSearch} placeholder={partLoading?"PART 검색 중…":"선택 사항 · PART Code·품명·사양 검색"} onChange={event=>choosePart(event.target.value)}/><datalist id={`${kind.toLowerCase()}-part-options`}>{visibleParts.map(item=><option key={item.id} value={partLabel(item)}/>)}</datalist></label></div>
    {selectedPart&&<div className="wv2-ecr-drawing-link"><FileText size={18}/><span><b>{selectedPart.partNumber} · {selectedPart.name}</b><small>{selectedPart.partType} · Rev.{selectedPart.revision}{selectedPart.spec?` · ${selectedPart.spec}`:""}</small></span></div>}
    {!partLoading&&partSearch.trim()&&!parts.length&&<p className="wv2-workflow-hint">조건에 맞는 PART가 없습니다. PART 연결 없이도 등록할 수 있습니다.</p>}
    <label><span>관련 도면</span><input list={`${kind.toLowerCase()}-drawing-options`} value={drawingSearch} placeholder={drawingLoading?"도면 검색 중…":"선택 사항 · 전사 도면코드·도면명·프로젝트 검색"} onChange={event=>chooseDrawing(event.target.value)}/><datalist id={`${kind.toLowerCase()}-drawing-options`}>{drawings.map(item=><option key={item.id} value={drawingLabel(item)}/>)}</datalist></label>
    {selectedDrawing&&<div className="wv2-ecr-drawing-link"><FileText size={18}/><span><b>{selectedDrawing.drawingCode||"도면코드 없음"} · {selectedDrawing.name}</b><small>{selectedDrawing.projectCode} · {selectedDrawing.projectName}{selectedDrawing.taskCode?` · 연결 Task ${selectedDrawing.taskCode} ${selectedDrawing.taskName||""}`:" · Task 연결 없음"}</small></span></div>}
    {drawingProjectMismatch&&<p className="wv2-workflow-hint">선택한 도면은 현재 프로젝트와 다른 프로젝트 소속입니다. 도면은 참조로 연결되며 해당 도면의 Task는 현재 Workflow에 연결하지 않습니다.</p>}
    {!drawingLoading&&drawingSearch.trim()&&!drawings.length&&<p className="wv2-workflow-hint">조건에 맞는 도면이 없습니다. 도면 연결 없이도 등록할 수 있습니다.</p>}
    {ecr?<><div className="two"><label><span>변경 제목 *</span><input value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label><span>설계변경 유형</span><select value={form.changeType||""} onChange={event=>setForm({...form,changeType:event.target.value})}><option value="">선택</option>{designChangeTypes.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label></div><div className="two"><label><span>우선순위</span><select value={form.priority} onChange={event=>setForm({...form,priority:event.target.value})}><option value="normal">보통</option><option value="high">높음</option><option value="urgent">긴급</option></select></label><label><span>처리기한</span><input type="date" value={form.dueDate||""} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label></div><label><span>변경 전 내용</span><textarea rows={3} value={form.beforeContent||""} onChange={event=>setForm({...form,beforeContent:event.target.value})}/></label><label><span>변경 후 내용</span><textarea rows={3} value={form.afterContent||""} onChange={event=>setForm({...form,afterContent:event.target.value})}/></label><label><span>변경 사유·영향</span><textarea rows={4} value={form.reason||""} onChange={event=>setForm({...form,reason:event.target.value})}/></label></>:<><div className="two"><label><span>문제 제목 *</span><input value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label><span>처리기한</span><input type="date" value={form.dueDate||""} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label></div><div className="three"><label><span>발생일</span><input type="date" value={form.occurredOn||""} onChange={event=>setForm({...form,occurredOn:event.target.value})}/></label><label><span>문제 유형</span><select value={form.issueType||""} onChange={event=>setForm({...form,issueType:event.target.value})}><option value="">선택</option>{qualityIssueTypes.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label><span>심각도</span><select value={form.severity||"medium"} onChange={event=>setForm({...form,severity:event.target.value})}><option value="low">낮음</option><option value="medium">보통</option><option value="high">높음</option><option value="critical">심각</option></select></label></div><label><span>문제 내용</span><textarea rows={4} value={form.description||""} onChange={event=>setForm({...form,description:event.target.value})}/></label><div className="two"><label><span>원인분석</span><textarea rows={4} value={form.rootCause||""} onChange={event=>setForm({...form,rootCause:event.target.value})}/></label><label><span>개선조치</span><textarea rows={4} value={form.correctiveAction||""} onChange={event=>setForm({...form,correctiveAction:event.target.value})}/></label></div><label><span>효과검증</span><textarea rows={3} value={form.effectivenessCheck||""} onChange={event=>setForm({...form,effectivenessCheck:event.target.value})}/></label></>}
  </div><aside className="wv2-create-workflow-summary assignees-only"><section className="wv2-workflow-line wv2-source-assignee-line"><header><h2>단계별 처리 담당자</h2><span>{optionsLoading?"조직 사용자를 불러오는 중…":"전체 조직의 활성 사용자 중에서 지정하세요."}</span></header>{steps.map((step,index)=><article key={`${index}-${step.name}`}><b>{index+1}</b><span><strong>{step.name}</strong><small>{actionLabels[step.actionType]} · {step.roleCode||step.assignmentRule}</small></span>{index===0?<em>요청자 자동</em>:<OrganizationAssigneeSelect users={users} value={assignees[String(index)]||""} onChange={value=>setAssignees({...assignees,[String(index)]:value})} required={step.actionType!=="REFERENCE"}/>}</article>)}{form.projectId&&!optionsLoading&&!steps.length&&<p className="wv2-workflow-hint">사용 가능한 Workflow 단계를 찾지 못했습니다.</p>}</section></aside></div>
  <section className="wv2-source-attachment-picker"><header><div><h2>관련 문서 첨부</h2></div><em>{activeAttachments.length+files.length}개</em></header>{activeAttachments.length>0&&<div className="wv2-source-attachment-list">{activeAttachments.map(item=><article key={item.id}><FileText size={18}/><span><b>{item.fileName}</b><small>{Math.max(1,Math.round(Number(item.fileSize||0)/1024))} KB · 기존 문서</small></span><button aria-label="첨부 삭제 예약" onClick={()=>setRemoveAttachmentIds(current=>[...current,item.id])}><Trash2 size={18}/></button></article>)}</div>}{files.length>0&&<div className="wv2-source-attachment-list">{files.map((file,index)=><article key={`${file.name}-${file.size}-${index}`}><FileText size={18}/><span><b>{file.name}</b><small>{Math.max(1,Math.round(file.size/1024))} KB · 새 문서</small></span><button aria-label="첨부 취소" onClick={()=>setFiles(current=>current.filter((_,cursor)=>cursor!==index))}><X size={18}/></button></article>)}</div>}<button type="button" className={`wv2-source-attachment-drop${dragging?" dragging":""}`} onClick={()=>fileInput.current?.click()} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);addFiles(event.dataTransfer.files)}}><Upload size={22}/><span><b>문서를 끌어 놓거나 선택하세요</b><small>여러 파일을 한 번에 첨부할 수 있습니다.</small></span></button><input ref={fileInput} hidden type="file" multiple onChange={event=>event.target.files&&addFiles(event.target.files)}/></section>{error&&<p className="wv2-workflow-error">{error}</p>}</main></section>;
}

function drawingLabel(item:DrawingOption){return `${item.drawingCode||"도면코드 없음"} · ${item.name} · ${item.projectCode} ${item.projectName}`}
