"use client";
import {useEffect,useRef,useState} from "react";
import {Check,ChevronRight,Clock3,FileText,PanelRightClose,PanelRightOpen,Pencil,RefreshCw,ShieldCheck,Trash2,Upload,X} from "lucide-react";

type WorkflowRow={id:string;workflowNumber:string;title:string;sourceType:string;dueDate?:string;status:string;currentStepOrder:number;projectCode:string;projectName:string;templateName:string;currentStepName?:string;currentAssigneeName?:string;stepCount:number;stepFlow?:string};
const statusLabels:Record<string,string>={draft:"임시저장",in_progress:"결재 진행 중",supplement:"보완",approved:"승인 완료",rejected:"반려",recalled:"회수"};
const actionLabels:Record<string,string>={WRITE:"작성",PROCESS:"처리",REVIEW:"검토",AGREEMENT:"합의",APPROVAL:"승인",REFERENCE:"참조"};
const workflowTypeLabels:Record<string,string>={GENERAL:"일반",ECR:"설계변경",QUALITY:"품질관리",GATE:"Gate"};
const workflowTypeLabel=(value?:string)=>workflowTypeLabels[String(value||"GENERAL").toUpperCase()]||value||"일반";
const json=async(response:Response)=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"요청을 처리하지 못했습니다.");return data};

export function WorkflowStageList({rows,onOpen}:{rows:WorkflowRow[];onOpen:(id:string)=>void}){
  return <div className="wv2-workflow-table stage-table"><header><span>워크플로우</span><span>대상 프로젝트</span><span>전체 단계</span><span>현재 단계·처리자</span><span>기한</span><span>상태</span><span/></header>{rows.map(row=>{const flow=String(row.stepFlow||"").split("~").filter(Boolean).map(value=>{const [name,status]=value.split("|");return {name,status}});return <button key={row.id} onClick={()=>onOpen(row.id)}><span className="workflow-primary"><b><em className="workflow-type-badge">{workflowTypeLabel(row.sourceType)}</em>{row.title}</b><small>{row.workflowNumber} · {row.templateName}</small></span><span><b>{row.projectName}</b><small>{row.projectCode}</small></span><span className="wv2-stage-flow">{flow.length?flow.map((step,index)=><i key={`${index}-${step.name}`} className={step.status} title={`${index+1}. ${step.name}`}><b>{index+1}</b><small>{step.name}</small></i>):<small>{row.currentStepOrder+1}/{row.stepCount}단계</small>}</span><span><b>{row.currentStepName||"작성"}</b><small>{row.currentAssigneeName||"미배정"}</small></span><span><b>{row.dueDate||"미정"}</b><small>{row.dueDate&&row.dueDate<new Date().toISOString().slice(0,10)&&row.status==="in_progress"?"지연":""}</small></span><em className={`status ${row.status}`}>{statusLabels[row.status]||row.status}</em><ChevronRight size={18}/></button>})}</div>;
}

export function WorkflowDetailPanel({id,onClose,onChanged,onOpenDocuments,onEdit,onDeleted}:{id:string;onClose:()=>void;onChanged:()=>void;onOpenDocuments:(deliverableId:string)=>void;onEdit?:(sourceId:string)=>void;onDeleted?:()=>void}){
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[comment,setComment]=useState(""),[revisionTarget,setRevisionTarget]=useState(""),[revisionNote,setRevisionNote]=useState(""),[file,setFile]=useState<File|null>(null),[dragging,setDragging]=useState(false),[wide,setWide]=useState(true),[sectionTab,setSectionTab]=useState<"workflow"|"documents">("workflow"),[deleteConfirm,setDeleteConfirm]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");const inputRef=useRef<HTMLInputElement>(null);
  const load=()=>{setLoading(true);fetch(`/api/workflows/${id}`,{cache:"no-store"}).then(json).then(async detail=>{const sourceType=String(detail.workflow?.source_type||"").toUpperCase(),sourceId=String(detail.workflow?.source_id||"");if(sourceId&&["ECR","QUALITY"].includes(sourceType)){const files=await fetch(`/api/workflows/source-attachments?sourceType=${sourceType}&sourceId=${encodeURIComponent(sourceId)}`,{cache:"no-store"}).then(json);detail.sourceAttachments=files.attachments??[]}setData(detail)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))};useEffect(()=>{setSectionTab("workflow");load()},[id]);
  const act=async(action:string)=>{setSaving(true);setError("");try{await fetch(`/api/workflows/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,comment})}).then(json);setComment("");load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"처리하지 못했습니다.")}finally{setSaving(false)}};
  const removeDraft=async()=>{setSaving(true);setError("");try{await fetch(`/api/workflows/${id}`,{method:"DELETE"}).then(json);onDeleted?.();onClose()}catch(reason){setError(reason instanceof Error?reason.message:"임시저장 Workflow를 삭제하지 못했습니다.")}finally{setSaving(false)}};
  const resetRevision=()=>{setRevisionTarget("");setRevisionNote("");setFile(null);setDragging(false);if(inputRef.current)inputRef.current.value=""};
  if(loading)return <aside className="wv2-workflow-detail wide"><div className="wv2-panel-loading"><RefreshCw size={30}/><b>Workflow 상세를 불러오는 중…</b></div></aside>;if(!data)return <aside className="wv2-workflow-detail wide"><header><div><small>WORKFLOW DETAIL</small><h2>상세정보를 불러오지 못했습니다.</h2></div><div className="panel-tools"><button aria-label="다시 시도" onClick={load}><RefreshCw size={18}/></button><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div></header><main><p className="wv2-workflow-error">{error||"잠시 후 다시 시도해 주세요."}</p></main></aside>;
  const w=data.workflow,steps=data.steps??[],documents=data.documents??[],linkedDocuments=data.linkedDocuments??[],sourceAttachments=data.sourceAttachments??[],current=steps.find((step:any)=>Number(step.step_order)===Number(w.current_step_order)),canAct=Boolean(data.permissions?.canAct),canManageDraft=w.status==="draft"&&Boolean(data.permissions?.isRequester||data.permissions?.isAdmin);
  const upload=async()=>{if(!file||!revisionTarget)return;setSaving(true);setError("");try{const body=new FormData();body.set("file",file);body.set("deliverableId",revisionTarget);body.set("note",revisionNote.trim());await fetch(`/api/workflows/${id}`,{method:"POST",body}).then(json);resetRevision();load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"Revision을 등록하지 못했습니다.")}finally{setSaving(false)}};
  return <aside className={`wv2-workflow-detail${wide?" wide":""}`}><header><div><small>{w.workflow_number}</small><h2>{w.title}</h2><p>{w.projectCode} · {w.projectName}</p></div><div className="panel-tools"><button aria-label={wide?"기본 너비":"넓게 보기"} onClick={()=>setWide(value=>!value)}>{wide?<PanelRightOpen size={18}/>:<PanelRightClose size={18}/>}</button><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div></header><nav className="wv2-workflow-detail-tabs"><button className={sectionTab==="workflow"?"active":""} onClick={()=>setSectionTab("workflow")}>워크플로우</button><button className={sectionTab==="documents"?"active":""} onClick={()=>setSectionTab("documents")}>문서·산출물 <em>{linkedDocuments.length+sourceAttachments.length}</em></button></nav><main>
    {sectionTab==="workflow"&&<>
      <section className="summary"><span className={`status ${w.status}`}>{statusLabels[w.status]||w.status}</span><dl><div><dt>요청자</dt><dd>{w.requesterName}</dd></div><div><dt>처리기한</dt><dd>{w.due_date||"미정"}</dd></div><div><dt>관련 Task</dt><dd>{w.taskCode?`${w.taskCode} ${w.taskName}`:"연결 없음"}</dd></div><div><dt>현재 처리자</dt><dd>{current?.assigneeName||"미배정"}</dd></div></dl>{w.request_content&&<p>{w.request_content}</p>}</section>
      {canManageDraft&&<section className="wv2-draft-management"><div><b>임시저장 관리</b><small>결재 요청 전까지 정보 수정과 삭제가 가능합니다.</small></div><div>{onEdit&&<button onClick={()=>onEdit(w.source_id||w.id)}><Pencil size={18}/>정보 수정</button>}{deleteConfirm?<><button onClick={()=>setDeleteConfirm(false)}>취소</button><button className="danger" disabled={saving} onClick={removeDraft}><Trash2 size={18}/>{saving?"삭제 중…":"삭제 확인"}</button></>:<button className="danger" onClick={()=>setDeleteConfirm(true)}><Trash2 size={18}/>삭제</button>}</div></section>}
      <section className="line"><h3>전체 단계·처리 담당자</h3>{steps.map((step:any)=><article key={step.id} className={step.status}><i>{step.status==="completed"?<Check size={18}/>:<Clock3 size={18}/>}</i><span><b>{step.step_order+1}. {step.name}</b><small>{actionLabels[step.action_type]} · {step.assigneeName||step.role_code||"미배정"}</small></span><em>{step.status==="completed"?"완료":step.status==="active"?"처리 중":step.status==="rejected"?"반려":"대기"}</em></article>)}</section>
      <section className="history"><h3>전체 처리 이력</h3>{(data.history??[]).map((item:any)=><article key={item.id}><span/><div><b>{item.actorName} · {item.action}</b><small>{item.stepName||"Workflow"} · {new Date(Number(item.created_at)*1000).toLocaleString("ko-KR")}</small>{item.comment&&<p>{item.comment}</p>}</div></article>)}</section>
      {w.official_document_id&&w.main_deliverable_id&&<button className="wv2-approved-document" onClick={()=>onOpenDocuments(w.main_deliverable_id)}><ShieldCheck size={20}/><span><b>승인문서 보기</b><small>{w.officialDocumentTitle||w.mainDocumentName} · 최종 Revision</small></span><ChevronRight size={18}/></button>}
      {!["approved","rejected"].includes(w.status)&&canAct&&<section className="action"><h3>{actionLabels[current?.action_type]||"처리"} 의견</h3><textarea rows={3} value={comment} onChange={event=>setComment(event.target.value)} placeholder={current?.comment_required?"처리 의견을 반드시 입력하세요.":"처리 의견을 입력하세요."}/><div>{["draft","supplement","recalled"].includes(w.status)?<button className="primary" disabled={saving} onClick={()=>act(w.status==="supplement"?"RESUBMIT":"SUBMIT")}>결재 요청</button>:<><button className="primary" disabled={saving} onClick={()=>act(current?.action_type||"COMPLETE")}>{actionLabels[current?.action_type]||"처리"}</button><button disabled={saving} onClick={()=>act("SUPPLEMENT")}>보완 요청</button><button className="danger" disabled={saving} onClick={()=>act("REJECT")}>반려</button>{data.permissions?.isRequester&&<button disabled={saving} onClick={()=>act("RECALL")}>회수</button>}</>}</div></section>}
      {!canAct&&!["approved","rejected"].includes(w.status)&&<p className="wv2-workflow-readonly">현재 단계 담당자만 의견 작성과 Revision 등록을 할 수 있습니다.</p>}
    </>}
    {sectionTab==="documents"&&<>
      <section className="wv2-workflow-documents"><header><div><h3>Workflow 문서·산출물</h3><small>결재 요청 시 확정된 {linkedDocuments.length}개 문서가 모든 단계를 함께 진행합니다.</small></div></header>{linkedDocuments.length?linkedDocuments.map((item:any)=>{const revisions=documents.filter((entry:any)=>entry.deliverableId===item.deliverableId),editing=revisionTarget===item.deliverableId;return <article className="workflow-document-card" key={item.deliverableId}><div className="document-main"><button className="document-open" onClick={()=>onOpenDocuments(item.deliverableId)}><FileText size={20}/><span><b>{item.name}</b><small>{item.documentKind==="drawing"?`${item.drawingCode||"도면"} · 도면`:item.category||"일반 산출물"} · {item.latestRevision?`Rev.${String(item.latestRevision).padStart(2,"0")}`:item.version||"파일 미등록"}</small></span><ChevronRight size={18}/></button><div className="document-actions">{item.latestVersionId&&<a href={`/api/projects/${w.project_id}/deliverables?versionId=${item.latestVersionId}`} target="_blank" rel="noreferrer">다운로드</a>}{canAct&&!["approved","rejected"].includes(w.status)&&<button onClick={()=>{if(editing){resetRevision();return}resetRevision();setRevisionTarget(item.deliverableId)}}>{editing?"취소":"Revision 등록"}</button>}</div></div>{revisions.length>0&&<details><summary>Workflow Revision 이력 {revisions.length}건</summary>{revisions.map((entry:any)=><a key={entry.id} href={`/api/projects/${w.project_id}/deliverables?versionId=${entry.versionId}`} target="_blank" rel="noreferrer">Rev.{String(entry.revision).padStart(2,"0")} · {entry.fileName}<small>{entry.createdBy} · {entry.changeReason||"변경 사유 없음"}</small></a>)}</details>}{editing&&<div className="document-revision-editor"><div className={dragging?"drop active":"drop"} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);if(event.dataTransfer.files.length!==1){setError("한 번에 파일 1개만 등록할 수 있습니다.");return}setFile(event.dataTransfer.files[0]||null)}} onClick={()=>inputRef.current?.click()}><Upload size={19}/><b>{file?.name||"개정 파일을 놓거나 클릭해 선택"}</b><small>현재 문서의 다음 Revision으로 등록됩니다.</small></div><input ref={inputRef} hidden type="file" onChange={event=>setFile(event.target.files?.[0]||null)}/><textarea rows={2} value={revisionNote} onChange={event=>setRevisionNote(event.target.value)} placeholder="변경 사유·비고"/><button className="primary" disabled={!file||saving} onClick={upload}>{saving?"등록 중…":"새 Revision 등록"}</button></div>}</article>}):<p className="document-empty">연결된 문서·산출물이 없습니다.</p>}</section>
      {sourceAttachments.length>0&&<section className="wv2-source-attachment-list"><h3>관련 첨부문서</h3>{sourceAttachments.map((item:any)=><a key={item.id} href={`/api/workflows/source-attachments?attachmentId=${item.id}`}><FileText size={18}/><span><b>{item.fileName}</b><small>{Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB</small></span></a>)}</section>}
    </>}
    {error&&<p className="wv2-workflow-error">{error}</p>}
  </main></aside>;
}
