"use client";
import {useEffect,useRef,useState} from "react";
import {Check,ChevronDown,ChevronRight,Clock3,FileText,PanelRightClose,PanelRightOpen,Pencil,RefreshCw,ShieldCheck,Trash2,Upload,X} from "lucide-react";
import {useAiContextSelection} from "./ai-context-selection";
import "./workflow-detail-panel-v2.css";

type WorkflowRow={id:string;workflowNumber:string;title:string;sourceType:string;dueDate?:string;status:string;currentStepOrder:number;projectCode:string;projectName:string;templateName:string;currentStepName?:string;currentAssigneeName?:string;stepCount:number;stepFlow?:string};
const statusLabels:Record<string,string>={draft:"임시저장",in_progress:"결재 진행 중",supplement:"보완",approved:"승인 완료",rejected:"반려",recalled:"회수"};
const actionLabels:Record<string,string>={WRITE:"작성",PROCESS:"처리",REVIEW:"검토",AGREEMENT:"합의",APPROVAL:"승인",REFERENCE:"참조"};
const workflowTypeLabels:Record<string,string>={GENERAL:"일반",ECR:"설계변경",QUALITY:"품질관리",GATE:"Gate"};
const workflowTypeLabel=(value?:string)=>workflowTypeLabels[String(value||"GENERAL").toUpperCase()]||value||"일반";
const severityLabels:Record<string,string>={low:"낮음",medium:"보통",high:"높음",critical:"심각"};
const priorityLabels:Record<string,string>={normal:"보통",high:"높음",urgent:"긴급"};
const json=async(response:Response)=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"요청을 처리하지 못했습니다.");return data};
const aiCheckboxStyle={width:15,height:15,margin:0,accentColor:"var(--teal)",cursor:"pointer",flex:"0 0 auto"} as const;
const fmtDateTime=(value:any)=>{const numeric=Number(value);if(!numeric)return "";return new Date(numeric*1000).toLocaleString("ko-KR")};

export function WorkflowStageList({rows,onOpen}:{rows:WorkflowRow[];onOpen:(id:string)=>void}){
  const selection=useAiContextSelection("워크플로우");
  const contextFor=(row:WorkflowRow)=>({id:row.id,kind:"워크플로우",title:`[${row.workflowNumber}] ${row.title}`,meta:`${row.projectName} · ${workflowTypeLabel(row.sourceType)} · 현재 단계 ${row.currentStepName||"작성"} · 처리자 ${row.currentAssigneeName||"미배정"} · 기한 ${row.dueDate||"미정"} · ${statusLabels[row.status]||row.status}`});
  const allSelected=Boolean(rows.length)&&rows.every(row=>selection.has(contextFor(row)));
  const toggleAll=()=>rows.forEach(row=>{const item=contextFor(row);if(allSelected?selection.has(item):!selection.has(item))selection.toggle(item)});
  return <div className="wv2-workflow-table stage-table"><header><span style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" aria-label="워크플로우 전체 선택" checked={allSelected} onChange={toggleAll} style={aiCheckboxStyle}/>워크플로우</span><span>대상 프로젝트</span><span>전체 단계</span><span>현재 단계·처리자</span><span>기한</span><span>상태</span><span/></header>{rows.map(row=>{const flow=String(row.stepFlow||"").split("~").filter(Boolean).map(value=>{const [name,status]=value.split("|");return {name,status}}),item=contextFor(row),checked=selection.has(item);return <button key={row.id} onClick={()=>onOpen(row.id)}><span className="workflow-primary" style={{display:"flex",alignItems:"flex-start",gap:8}}><input type="checkbox" aria-label="워크플로우 AI 선택" checked={checked} onClick={event=>event.stopPropagation()} onChange={event=>{event.stopPropagation();selection.toggle(item)}} style={{...aiCheckboxStyle,marginTop:2}}/><span style={{display:"grid",minWidth:0}}><b><em className="workflow-type-badge">{workflowTypeLabel(row.sourceType)}</em>{row.title}</b><small>{row.workflowNumber} · {row.templateName}</small></span></span><span><b>{row.projectName}</b><small>{row.projectCode}</small></span><span className="wv2-stage-flow">{flow.length?flow.map((step,index)=><i key={`${index}-${step.name}`} className={step.status} title={`${index+1}. ${step.name}`}><b>{index+1}</b><small>{step.name}</small></i>):<small>{row.currentStepOrder+1}/{row.stepCount}단계</small>}</span><span><b>{row.currentStepName||"작성"}</b><small>{row.currentAssigneeName||"미배정"}</small></span><span><b>{row.dueDate||"미정"}</b><small>{row.dueDate&&row.dueDate<new Date().toISOString().slice(0,10)&&row.status==="in_progress"?"지연":""}</small></span><em className={`status ${row.status}`}>{statusLabels[row.status]||row.status}</em><ChevronRight size={18}/></button>})}</div>;
}

export function WorkflowDetailPanel({id,onClose,onChanged,onOpenDocuments,onEdit,onDeleted}:{id:string;onClose:()=>void;onChanged:()=>void;onOpenDocuments:(deliverableId:string)=>void;onEdit?:(sourceId:string)=>void;onDeleted?:()=>void}){
  const documentSelection=useAiContextSelection("Workflow 문서·산출물");
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[comment,setComment]=useState(""),[wide,setWide]=useState(true),[sectionTab,setSectionTab]=useState<"workflow"|"request"|"documents">("workflow"),[deleteConfirm,setDeleteConfirm]=useState(false),[saving,setSaving]=useState(false),[artifactUploading,setArtifactUploading]=useState(false),[error,setError]=useState("");
  const artifactInputRef=useRef<HTMLInputElement>(null);
  const load=()=>{setLoading(true);setError("");fetch(`/api/workflows/${id}`,{cache:"no-store"}).then(json).then(async detail=>{const sourceType=String(detail.workflow?.source_type||"").toUpperCase(),sourceId=String(detail.workflow?.source_id||"");if(sourceId&&["ECR","QUALITY"].includes(sourceType)){const endpoint=sourceType==="ECR"?"/api/ecr":"/api/quality";const source=await fetch(`${endpoint}?id=${encodeURIComponent(sourceId)}`,{cache:"no-store"}).then(json);detail.sourceInfo=source.item??null;detail.sourceAttachments=source.attachments??[]}setData(detail)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))};
  useEffect(()=>{setSectionTab("workflow");load()},[id]);
  const act=async(action:string)=>{setSaving(true);setError("");try{await fetch(`/api/workflows/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,comment})}).then(json);setComment("");load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"처리하지 못했습니다.")}finally{setSaving(false)}};
  const removeDraft=async()=>{setSaving(true);setError("");try{await fetch(`/api/workflows/${id}`,{method:"DELETE"}).then(json);onDeleted?.();onClose()}catch(reason){setError(reason instanceof Error?reason.message:"임시저장 Workflow를 삭제하지 못했습니다.")}finally{setSaving(false)}};
  const uploadStepArtifacts=async(files:FileList|null)=>{if(!files?.length)return;setArtifactUploading(true);setError("");try{for(const selected of Array.from(files)){const body=new FormData();body.set("mode","STEP_ARTIFACT");body.set("file",selected);await fetch(`/api/workflows/${id}`,{method:"POST",body}).then(json)}load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"단계 산출물을 등록하지 못했습니다.")}finally{setArtifactUploading(false);if(artifactInputRef.current)artifactInputRef.current.value=""}};
  if(loading)return <aside className="wv2-panel wide"><div className="wv2-panel-loading"><RefreshCw size={30}/><b>Workflow 상세를 불러오는 중…</b></div></aside>;
  if(!data)return <aside className="wv2-panel wide"><header><div><small>WORKFLOW DETAIL</small><h2>상세정보를 불러오지 못했습니다.</h2><span>{error||"잠시 후 다시 시도해 주세요."}</span></div><div><button aria-label="다시 시도" onClick={load}><RefreshCw size={18}/></button><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div></header></aside>;
  const w=data.workflow,steps=data.steps??[],history=data.history??[],documents=data.documents??[],linkedDocuments=data.linkedDocuments??[],sourceAttachments=data.sourceAttachments??[],sourceInfo=data.sourceInfo??null,current=steps.find((step:any)=>Number(step.step_order)===Number(w.current_step_order)),canAct=Boolean(data.permissions?.canAct),canManageDraft=w.status==="draft"&&Boolean(data.permissions?.isRequester||data.permissions?.isAdmin),sourceType=String(w.source_type||"GENERAL").toUpperCase();
  const currentNumber=Number(w.current_step_order||0)+1,totalSteps=steps.length;
  const documentHasStep=(deliverableId:string)=>documents.some((entry:any)=>String(entry.deliverableId)===String(deliverableId));
  const documentsForStep=(step:any)=>{const stepIds=new Set(documents.filter((entry:any)=>String(entry.stepId)===String(step.id)).map((entry:any)=>String(entry.deliverableId))),items=linkedDocuments.filter((item:any)=>stepIds.has(String(item.deliverableId)));if(Number(step.step_order)===0)for(const item of linkedDocuments)if(!documentHasStep(item.deliverableId)&&!items.some((row:any)=>row.deliverableId===item.deliverableId))items.push(item);return items};
  const documentContextFor=(item:any,step:any)=>({id:item.deliverableId,kind:"문서",title:item.name,meta:`${w.workflow_number} · ${Number(step.step_order)+1}. ${step.name} · 담당 ${step.assigneeName||step.role_code||"미배정"} · ${w.projectName}`,projectName:w.projectName,projectId:w.project_id,fileAttached:Boolean(item.latestVersionId)});
  const currentOutputs=current?documentsForStep(current):[];
  return <aside className={`wv2-panel${wide?" wide":""}`}>
    <div className="wv2-resize"/>
    <header><div><small>{w.workflow_number}</small><h2>{w.title}</h2><span>{w.projectCode} · {w.projectName}</span></div><div><button aria-label={wide?"기본 너비":"넓게 보기"} onClick={()=>setWide(value=>!value)}>{wide?<PanelRightOpen size={18}/>:<PanelRightClose size={18}/>}</button><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div></header>
    <nav><button className={sectionTab==="workflow"?"active":""} onClick={()=>setSectionTab("workflow")}>워크플로우</button><button className={sectionTab==="request"?"active":""} onClick={()=>setSectionTab("request")}>요청정보</button><button className={sectionTab==="documents"?"active":""} onClick={()=>setSectionTab("documents")}>문서·산출물</button></nav>
    <section className="wv2-panel-body wv2-workflow-panel-content">
      {sectionTab==="workflow"&&<>
        <section className="wv2-workflow-quick-status"><span className={`status ${w.status}`}>{statusLabels[w.status]||w.status}</span><b>현재 {currentNumber}/{totalSteps} · {current?.name||"단계 미정"}</b><span>담당 {current?.assigneeName||"미배정"}</span><span>기한 {w.due_date||"미정"}</span></section>
        {canManageDraft&&<section className="wv2-draft-management compact"><div><b>임시저장 관리</b><small>결재 요청 전까지 수정·삭제할 수 있습니다.</small></div><div>{onEdit&&<button onClick={()=>onEdit(w.source_id||w.id)}><Pencil size={17}/>정보 수정</button>}{deleteConfirm?<><button onClick={()=>setDeleteConfirm(false)}>취소</button><button className="danger" disabled={saving} onClick={removeDraft}><Trash2 size={17}/>{saving?"삭제 중…":"삭제 확인"}</button></>:<button className="danger" onClick={()=>setDeleteConfirm(true)}><Trash2 size={17}/>삭제</button>}</div></section>}
        <section className="wv2-workflow-step-history"><header><h3>단계별 처리 현황</h3><small>단계·담당자·처리 결과·의견을 한 번에 확인합니다.</small></header>{steps.map((step:any)=>{const related=history.filter((item:any)=>String(item.stepName||"")===String(step.name||"")||Number(item.step_order)===Number(step.step_order)),comments=related.filter((item:any)=>item.comment),outputCount=documentsForStep(step).length;return <article key={step.id} className={`step-card ${step.status}`}><i>{step.status==="completed"?<Check size={17}/>:<Clock3 size={17}/>}</i><div><b>{Number(step.step_order)+1}. {step.name}</b><small>{actionLabels[step.action_type]} · {step.assigneeName||step.role_code||"미배정"}{related.length?` · 처리 ${related.length}건`:""}{outputCount?` · 산출물 ${outputCount}건`:""}</small>{comments.slice(-2).map((item:any)=><p key={item.id}><strong>{item.actorName}</strong> {item.comment}<em>{fmtDateTime(item.created_at)}</em></p>)}</div><span>{step.status==="completed"?"완료":step.status==="active"?"처리 중":step.status==="rejected"?"반려":"대기"}</span></article>})}</section>
        {!["approved","rejected"].includes(w.status)&&canAct&&<section className="action wv2-current-step-action"><div className="wv2-current-step-head"><h3>{currentNumber}. {current?.name||"현재 단계"} · {actionLabels[current?.action_type]||"처리"}</h3><button className="wv2-step-artifact-add" disabled={artifactUploading} onClick={()=>artifactInputRef.current?.click()}><Upload size={15}/>{artifactUploading?"등록 중…":"산출물 추가"}</button><input ref={artifactInputRef} hidden multiple type="file" onChange={event=>void uploadStepArtifacts(event.target.files)}/></div><textarea rows={3} value={comment} onChange={event=>setComment(event.target.value)} placeholder={current?.comment_required?"처리 의견을 반드시 입력하세요.":"처리 의견을 입력하세요."}/><div className="wv2-current-step-actions">{["draft","supplement","recalled"].includes(w.status)?<button className="primary" disabled={saving} onClick={()=>act(w.status==="supplement"?"RESUBMIT":"SUBMIT")}>결재 요청</button>:<><button className="primary" disabled={saving} onClick={()=>act(current?.action_type||"COMPLETE")}>{actionLabels[current?.action_type]||"처리"}</button><button disabled={saving} onClick={()=>act("SUPPLEMENT")}>보완 요청</button><button className="danger" disabled={saving} onClick={()=>act("REJECT")}>반려</button>{data.permissions?.isRequester&&<button disabled={saving} onClick={()=>act("RECALL")}>회수</button>}</>}</div>{currentOutputs.length>0&&<div className="wv2-current-step-files"><small>등록 산출물 {currentOutputs.length}건</small>{currentOutputs.map((item:any)=><button key={item.deliverableId} onClick={()=>onOpenDocuments(item.deliverableId)}><FileText size={15}/><span>{item.name}</span><ChevronRight size={14}/></button>)}</div>}</section>}
        {!canAct&&!["approved","rejected"].includes(w.status)&&<p className="wv2-workflow-readonly">현재 단계 담당자만 처리 의견과 산출물을 등록할 수 있습니다.</p>}
        {w.official_document_id&&w.main_deliverable_id&&<button className="wv2-approved-document" onClick={()=>onOpenDocuments(w.main_deliverable_id)}><ShieldCheck size={20}/><span><b>승인문서 보기</b><small>{w.officialDocumentTitle||w.mainDocumentName} · 최종 Revision</small></span><ChevronRight size={18}/></button>}
        <details className="wv2-workflow-audit-history"><summary><span>상세 처리 이력 {history.length}건</span><ChevronDown size={16}/></summary><div>{history.map((item:any)=><article key={item.id}><span/><div><b>{item.actorName} · {item.action}</b><small>{item.stepName||"Workflow"} · {fmtDateTime(item.created_at)}</small>{item.comment&&<p>{item.comment}</p>}</div></article>)}</div></details>
      </>}
      {sectionTab==="request"&&<RequestInformation sourceType={sourceType} sourceInfo={sourceInfo} workflow={w} attachments={sourceAttachments}/>} 
      {sectionTab==="documents"&&<section className="wv2-workflow-stage-documents"><header><div><h3>단계별 문서·산출물</h3><small>Workflow 단계와 담당자를 기준으로 등록 산출물을 확인합니다. 체크한 문서는 공통 AI 대화 문맥에 추가됩니다.</small></div></header><div className="wv2-workflow-stage-document-list">{steps.map((step:any)=>{const items=documentsForStep(step);return <article className={`wv2-workflow-stage-document-group ${step.status}`} key={step.id}><header><div><b>{Number(step.step_order)+1}. {step.name}</b><small>{actionLabels[step.action_type]} · 담당 {step.assigneeName||step.role_code||"미배정"}</small></div><span>{step.status==="completed"?"완료":step.status==="active"?"처리 중":step.status==="rejected"?"반려":"대기"}</span></header><div>{items.length?items.map((item:any)=>{const contextItem=documentContextFor(item,step),checked=documentSelection.has(contextItem);return <div className="wv2-workflow-stage-document-row" key={`${step.id}-${item.deliverableId}`}><input type="checkbox" aria-label={`${item.name} AI 선택`} checked={checked} onChange={()=>documentSelection.toggle(contextItem)} style={aiCheckboxStyle}/><button className="document-open" onClick={()=>onOpenDocuments(item.deliverableId)}><FileText size={18}/><span><b>{item.name}</b><small>{item.documentKind==="drawing"?`${item.drawingCode||"도면"} · 도면`:item.category||"일반 산출물"}{item.latestRevision?` · Rev.${String(item.latestRevision).padStart(2,"0")}`:""}</small></span></button>{item.latestVersionId?<a href={`/api/projects/${w.project_id}/deliverables?versionId=${item.latestVersionId}`} target="_blank" rel="noreferrer">다운로드</a>:<span className="no-file">파일 없음</span>}</div>}):<p>등록된 문서·산출물이 없습니다.</p>}</div></article>})}</div></section>}
      {error&&<p className="wv2-workflow-error">{error}</p>}
    </section>
  </aside>;
}

function RequestInformation({sourceType,sourceInfo,workflow,attachments}:{sourceType:string;sourceInfo:any;workflow:any;attachments:any[]}){
  if(sourceType==="ECR"&&sourceInfo)return <section className="wv2-request-info"><header><small>ENGINEERING CHANGE REQUEST</small><h3>{sourceInfo.ecrNumber} · {sourceInfo.title}</h3></header><dl><div><dt>설계변경 유형</dt><dd>{sourceInfo.changeType||"미지정"}</dd></div><div><dt>우선순위</dt><dd>{priorityLabels[sourceInfo.priority]||sourceInfo.priority||"보통"}</dd></div><div><dt>처리기한</dt><dd>{sourceInfo.dueDate||"미정"}</dd></div><div><dt>관련 Task</dt><dd>{workflow.taskCode?`${workflow.taskCode} ${workflow.taskName}`:"연결 없음"}</dd></div></dl>{sourceInfo.beforeContent&&<InfoBlock title="변경 전 내용" value={sourceInfo.beforeContent}/>} {sourceInfo.afterContent&&<InfoBlock title="변경 후 내용" value={sourceInfo.afterContent}/>} {sourceInfo.reason&&<InfoBlock title="변경 사유" value={sourceInfo.reason}/>} {sourceInfo.impactContent&&<InfoBlock title="영향" value={sourceInfo.impactContent}/>}<AttachmentSummary attachments={attachments}/></section>;
  if(sourceType==="QUALITY"&&sourceInfo)return <section className="wv2-request-info"><header><small>QUALITY CASE</small><h3>{sourceInfo.qualityNumber} · {sourceInfo.title}</h3></header><dl><div><dt>발생일</dt><dd>{sourceInfo.occurredOn||"미정"}</dd></div><div><dt>문제 유형</dt><dd>{sourceInfo.issueType||"미지정"}</dd></div><div><dt>심각도</dt><dd>{severityLabels[sourceInfo.severity]||sourceInfo.severity||"보통"}</dd></div><div><dt>처리기한</dt><dd>{sourceInfo.dueDate||"미정"}</dd></div></dl>{sourceInfo.description&&<InfoBlock title="문제 내용" value={sourceInfo.description}/>} {sourceInfo.rootCause&&<InfoBlock title="원인분석" value={sourceInfo.rootCause}/>} {sourceInfo.correctiveAction&&<InfoBlock title="개선조치" value={sourceInfo.correctiveAction}/>} {sourceInfo.effectivenessCheck&&<InfoBlock title="효과검증" value={sourceInfo.effectivenessCheck}/>}<AttachmentSummary attachments={attachments}/></section>;
  return <section className="wv2-request-info"><header><small>{workflowTypeLabel(sourceType)} WORKFLOW REQUEST</small><h3>{workflow.title}</h3></header><dl><div><dt>요청자</dt><dd>{workflow.requesterName||"미지정"}</dd></div><div><dt>우선순위</dt><dd>{priorityLabels[workflow.priority]||workflow.priority||"보통"}</dd></div><div><dt>처리기한</dt><dd>{workflow.due_date||"미정"}</dd></div><div><dt>관련 Task</dt><dd>{workflow.taskCode?`${workflow.taskCode} ${workflow.taskName}`:"연결 없음"}</dd></div></dl><InfoBlock title="요청내용" value={workflow.request_content||"등록된 요청내용이 없습니다."}/><AttachmentSummary attachments={attachments}/></section>;
}
function InfoBlock({title,value}:{title:string;value:string}){return <section className="wv2-request-block"><h4>{title}</h4><p>{value}</p></section>}
function AttachmentSummary({attachments}:{attachments:any[]}){return <section className="wv2-request-attachments"><h4>요청 첨부문서 <em>{attachments.length}</em></h4>{attachments.length?attachments.map(item=><a key={item.id} href={`/api/workflows/source-attachments?attachmentId=${item.id}`}><FileText size={17}/><span><b>{item.fileName}</b><small>{Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB</small></span></a>):<p>등록된 첨부문서가 없습니다.</p>}</section>}
