/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,requireProjectAccess,resolveRequestContext} from "../../../db/request-context";
import {deleteDraftWorkflow,updateDraftWorkflow} from "../workflows/draft-management";
import {readSourceUpload,syncSourceAttachments} from "../workflows/source-files";
import {createWorkflowInstance,nowSeconds,seedDefaultWorkflowTemplates,workflowDb} from "../workflows/shared";

async function ensureEcrDrawingCompatibility(db:any){try{await db.prepare("ALTER TABLE design_change_requests ADD COLUMN drawing_id TEXT").run()}catch{}try{await db.prepare("ALTER TABLE design_change_requests ADD COLUMN change_type TEXT").run()}catch{}try{await db.prepare("ALTER TABLE deliverables ADD COLUMN document_kind TEXT NOT NULL DEFAULT 'document'").run()}catch{}try{await db.prepare("ALTER TABLE deliverables ADD COLUMN drawing_code TEXT").run()}catch{}}
async function drawingFor(db:any,companyId:string,projectId:string,drawingId:string){return db.prepare("SELECT d.id,d.task_id AS taskId,d.drawing_code AS drawingCode,d.name,t.wbs_code AS taskCode,t.name AS taskName FROM deliverables d LEFT JOIN wbs_tasks t ON t.id=d.task_id JOIN projects p ON p.id=d.project_id WHERE d.id=? AND d.project_id=? AND p.company_id=? AND COALESCE(d.document_kind,'document')='drawing'").bind(drawingId,projectId,companyId).first() as Promise<{id:string;taskId?:string;drawingCode?:string;name:string;taskCode?:string;taskName?:string}|null>}

export async function GET(request:Request){
 const db=await workflowDb();await ensureEcrDrawingCompatibility(db);let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경을 불러오지 못했습니다."},{status:500})}
 const url=new URL(request.url),id=url.searchParams.get("id")||"",projectId=url.searchParams.get("projectId")||"";
 if(id){const item=await db.prepare("SELECT e.id,e.project_id AS projectId,e.task_id AS taskId,e.drawing_id AS drawingId,e.ecr_number AS ecrNumber,e.title,e.change_type AS changeType,e.before_content AS beforeContent,e.after_content AS afterContent,e.reason,e.impact_content AS impactContent,e.priority,e.status,e.workflow_id AS workflowId,w.due_date AS dueDate FROM design_change_requests e LEFT JOIN workflow_instances w ON w.id=e.workflow_id WHERE e.id=? AND e.company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"설계변경을 찾을 수 없습니다."},{status:404});try{await requireProjectAccess(db,context,item.projectId)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경 접근 권한이 없습니다."},{status:403})}const attachments=await db.prepare("SELECT id,file_name AS fileName,file_size AS fileSize,content_type AS contentType FROM workflow_source_attachments WHERE company_id=? AND source_type='ECR' AND source_id=? ORDER BY created_at,id").bind(context.companyId,id).all();return Response.json({item,attachments:attachments.results??[]})}
 const rows=await db.prepare(`SELECT e.id,e.ecr_number AS ecrNumber,e.title,e.change_type AS changeType,e.change_target AS changeTarget,e.priority,e.status,e.requested_at AS requestedAt,e.workflow_id AS workflowId,p.id AS projectId,p.code AS projectCode,p.name AS projectName,w.status AS workflowStatus,w.current_step_order AS currentStepOrder,w.due_date AS dueDate,cs.name AS currentStepName,cu.name AS currentAssigneeName,(SELECT COUNT(*) FROM workflow_instance_steps x WHERE x.workflow_id=w.id) AS stepCount,(SELECT group_concat(flow.name||'|'||flow.status,'~') FROM (SELECT name,status FROM workflow_instance_steps WHERE workflow_id=w.id ORDER BY step_order) flow) AS stepFlow,e.drawing_id AS drawingId,d.drawing_code AS drawingCode,d.name AS drawingName,t.wbs_code AS taskCode,t.name AS taskName FROM design_change_requests e JOIN projects p ON p.id=e.project_id LEFT JOIN workflow_instances w ON w.id=e.workflow_id LEFT JOIN workflow_instance_steps cs ON cs.workflow_id=w.id AND cs.step_order=w.current_step_order LEFT JOIN users cu ON cu.id=cs.assignee_user_id LEFT JOIN deliverables d ON d.id=e.drawing_id LEFT JOIN wbs_tasks t ON t.id=e.task_id WHERE e.company_id=? ${projectId?"AND e.project_id=?":""} ORDER BY e.updated_at DESC`).bind(context.companyId,...(projectId?[projectId]:[])).all();return Response.json({items:rows.results??[]});
}

export async function POST(request:Request){
 const db=await workflowDb();await ensureEcrDrawingCompatibility(db);let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"등록 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;
 if(!input.projectId||!input.title?.trim())return Response.json({error:"프로젝트와 변경 제목을 입력해 주세요."},{status:400});if(!input.drawingId)return Response.json({error:"설계변경 대상 도면을 선택해 주세요."},{status:400});try{await requireProjectAccess(db,context,input.projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"프로젝트 접근 권한이 없습니다."},{status:403})}
 const drawing=await drawingFor(db,context.companyId,input.projectId,input.drawingId);if(!drawing)return Response.json({error:"선택한 프로젝트의 도면을 찾을 수 없습니다."},{status:404});const taskId=drawing.taskId||null,changeTarget=[drawing.drawingCode,drawing.name].filter(Boolean).join(" · "),now=nowSeconds(),id=crypto.randomUUID(),seq=await db.prepare("SELECT COUNT(*) AS count FROM design_change_requests WHERE company_id=?").bind(context.companyId).first<{count:number}>(),number=`ECR-${new Date().toISOString().slice(0,4)}-${String(Number(seq?.count||0)+1).padStart(4,"0")}`;
 await db.prepare("INSERT INTO design_change_requests (id,company_id,project_id,task_id,drawing_id,ecr_number,title,change_type,change_target,before_content,after_content,reason,impact_content,priority,requester_user_id,requested_at,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'draft',?,?)").bind(id,context.companyId,input.projectId,taskId,drawing.id,number,input.title.trim(),input.changeType||null,changeTarget,input.beforeContent||null,input.afterContent||null,input.reason||null,input.impactContent||null,input.priority||"normal",context.userId,now,now,now).run();
 try{const workflow=await createWorkflowInstance(db,context,{projectId:input.projectId,taskId:taskId||undefined,templateCode:"EC_ACTION",title:`[${number}] ${input.title.trim()}`,requestContent:input.reason||input.afterContent,priority:input.priority,dueDate:input.dueDate||undefined,sourceType:"ECR",sourceId:id,assignees:input.assignees,submit:Boolean(input.submit)});await db.prepare("UPDATE design_change_requests SET workflow_id=?,status=?,updated_at=? WHERE id=?").bind(workflow.id,workflow.status,now,id).run();await syncSourceAttachments(db,context,{projectId:input.projectId,sourceType:"ECR",sourceId:id,files});return Response.json({id,ecrNumber:number,drawing,workflow},{status:201})}catch(reason){return Response.json({id,ecrNumber:number,error:reason instanceof Error?reason.message:"설계변경 Workflow를 생성하지 못했습니다."},{status:400})}
}

export async function PATCH(request:Request){
 const db=await workflowDb();await ensureEcrDrawingCompatibility(db);let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"수정 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;if(!input.id)return Response.json({error:"수정할 설계변경이 필요합니다."},{status:400});
 const current=await db.prepare("SELECT id,project_id AS projectId,ecr_number AS ecrNumber,workflow_id AS workflowId FROM design_change_requests WHERE id=? AND company_id=?").bind(input.id,context.companyId).first<any>();if(!current)return Response.json({error:"설계변경을 찾을 수 없습니다."},{status:404});try{await requireProjectAccess(db,context,current.projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경 수정 권한이 없습니다."},{status:403})}
 const drawing=await drawingFor(db,context.companyId,current.projectId,input.drawingId);if(!drawing)return Response.json({error:"변경 대상 도면을 찾을 수 없습니다."},{status:404});await updateDraftWorkflow(db,context,current.workflowId,{title:`[${current.ecrNumber}] ${String(input.title||"").trim()}`,taskId:drawing.taskId||"",requestContent:input.reason||input.afterContent,priority:input.priority,dueDate:input.dueDate,assignees:input.assignees});
 const now=nowSeconds(),changeTarget=[drawing.drawingCode,drawing.name].filter(Boolean).join(" · ");await db.prepare("UPDATE design_change_requests SET task_id=?,drawing_id=?,title=?,change_type=?,change_target=?,before_content=?,after_content=?,reason=?,impact_content=?,priority=?,updated_at=? WHERE id=?").bind(drawing.taskId||null,drawing.id,String(input.title||"").trim(),input.changeType||null,changeTarget,input.beforeContent||null,input.afterContent||null,input.reason||null,input.impactContent||null,input.priority||"normal",now,input.id).run();await syncSourceAttachments(db,context,{projectId:current.projectId,sourceType:"ECR",sourceId:input.id,files,removeAttachmentIds:input.removeAttachmentIds});return Response.json({ok:true,id:input.id,workflowId:current.workflowId});
}

export async function DELETE(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);const id=new URL(request.url).searchParams.get("id")||"",item=await db.prepare("SELECT workflow_id AS workflowId FROM design_change_requests WHERE id=? AND company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"설계변경을 찾을 수 없습니다."},{status:404});return Response.json(await deleteDraftWorkflow(db,context,item.workflowId))}catch(reason){return contextErrorResponse(reason)??Response.json({error:reason instanceof Error?reason.message:"설계변경을 삭제하지 못했습니다."},{status:400})}}
