import { integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const audit = {
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
};

export const companies = sqliteTable("companies", {
  id: text("id").primaryKey(), name: text("name").notNull(), code: text("code").notNull(), status: text("status").notNull().default("active"), ...audit,
}, table => [uniqueIndex("companies_code_uq").on(table.code)]);

export const organizations = sqliteTable("organizations", {
  id: text("id").primaryKey(), companyId: text("company_id").notNull().references(() => companies.id), parentId: text("parent_id"), name: text("name").notNull(), code: text("code").notNull(), sortOrder: integer("sort_order").notNull().default(0), ...audit,
}, table => [uniqueIndex("organizations_company_code_uq").on(table.companyId, table.code)]);

export const users = sqliteTable("users", {
  id: text("id").primaryKey(), companyId: text("company_id").notNull().references(() => companies.id), organizationId: text("organization_id").references(() => organizations.id), email: text("email").notNull(), name: text("name").notNull(), status: text("status").notNull().default("invited"), avatarKey: text("avatar_key").notNull().default("avatar-01"), ...audit,
}, table => [uniqueIndex("users_company_email_uq").on(table.companyId, table.email)]);

export const roles = sqliteTable("roles", { id:text("id").primaryKey(), companyId:text("company_id").notNull().references(() => companies.id), code:text("code").notNull(), name:text("name").notNull(), scope:text("scope").notNull(), permissions:text("permissions", { mode:"json" }).notNull(), ...audit }, table => [uniqueIndex("roles_company_code_uq").on(table.companyId, table.code)]);
export const userRoles = sqliteTable("user_roles", { userId:text("user_id").notNull().references(() => users.id), roleId:text("role_id").notNull().references(() => roles.id), projectId:text("project_id") }, table => [primaryKey({columns:[table.userId,table.roleId]})]);

export const commonCodes = sqliteTable("common_codes", { id:text("id").primaryKey(), companyId:text("company_id").notNull().references(() => companies.id), groupCode:text("group_code").notNull(), code:text("code").notNull(), label:text("label").notNull(), version:integer("version").notNull().default(1), sortOrder:integer("sort_order").notNull().default(0), enabled:integer("enabled",{mode:"boolean"}).notNull().default(true), ...audit }, table => [uniqueIndex("common_codes_version_uq").on(table.companyId, table.groupCode, table.code, table.version)]);
export const templates = sqliteTable("templates", { id:text("id").primaryKey(), companyId:text("company_id").notNull().references(() => companies.id), code:text("code").notNull(), name:text("name").notNull(), status:text("status").notNull().default("draft"), ...audit }, table => [uniqueIndex("templates_company_code_uq").on(table.companyId, table.code)]);
export const templateVersions = sqliteTable("template_versions", { id:text("id").primaryKey(), templateId:text("template_id").notNull().references(() => templates.id), version:text("version").notNull(), definition:text("definition",{mode:"json"}).notNull(), publishedAt:integer("published_at",{mode:"timestamp"}), createdBy:text("created_by").notNull().references(() => users.id), ...audit }, table => [uniqueIndex("template_versions_template_version_uq").on(table.templateId, table.version)]);

export const projectsDb = sqliteTable("projects", { id:text("id").primaryKey(), companyId:text("company_id").notNull().references(() => companies.id), templateVersionId:text("template_version_id").notNull().references(() => templateVersions.id), code:text("code").notNull(), name:text("name").notNull(), customerName:text("customer_name"), partnerId:text("partner_id"), projectTypeId:text("project_type_id"), startDate:text("start_date").notNull(), endDate:text("end_date").notNull(), status:text("status").notNull().default("preparing"), templateSnapshot:text("template_snapshot",{mode:"json"}).notNull(), ...audit }, table => [uniqueIndex("projects_company_code_uq").on(table.companyId, table.code)]);
export const projectMembers = sqliteTable("project_members", { projectId:text("project_id").notNull().references(() => projectsDb.id), userId:text("user_id").notNull().references(() => users.id), projectRole:text("project_role").notNull(), ...audit }, table => [primaryKey({columns:[table.projectId,table.userId]})]);
export const projectRoles = sqliteTable("project_roles", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(() => projectsDb.id), code:text("code").notNull(), name:text("name").notNull(), sortOrder:integer("sort_order").notNull().default(0), ...audit }, table => [uniqueIndex("project_roles_project_code_uq").on(table.projectId,table.code)]);
export const wbsTasks = sqliteTable("wbs_tasks", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(() => projectsDb.id), wbsCode:text("wbs_code").notNull(), parentId:text("parent_id"), level:integer("level").notNull(), sortOrder:integer("sort_order").notNull(), kind:text("kind").notNull().default("task"), name:text("name").notNull(), taskType:text("task_type").notNull().default("normal"), durationDays:integer("duration_days").notNull().default(1), plannedStart:text("planned_start"), plannedEnd:text("planned_end"), predecessorId:text("predecessor_id"), roleCode:text("role_code"), assigneeUserId:text("assignee_user_id"), progress:integer("progress").notNull().default(0), status:text("status").notNull().default("planned"), completionActor:text("completion_actor").notNull().default("assignee"), completionCriteria:text("completion_criteria"), ...audit }, table => [uniqueIndex("wbs_tasks_project_code_uq").on(table.projectId,table.wbsCode)]);
export const projectBaselines = sqliteTable("project_baselines", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(()=>projectsDb.id,{onDelete:"cascade"}), version:integer("version").notNull(), name:text("name").notNull(), capturedAt:integer("captured_at",{mode:"timestamp"}).notNull(), capturedBy:text("captured_by"), isActive:integer("is_active",{mode:"boolean"}).notNull().default(true) }, table=>[uniqueIndex("project_baselines_project_version_uq").on(table.projectId,table.version)]);
export const projectBaselineTasks = sqliteTable("project_baseline_tasks", { baselineId:text("baseline_id").notNull().references(()=>projectBaselines.id,{onDelete:"cascade"}), taskId:text("task_id").notNull(), wbsCode:text("wbs_code").notNull(), name:text("name").notNull(), plannedStart:text("planned_start"), plannedEnd:text("planned_end"), durationDays:integer("duration_days").notNull(), sortOrder:integer("sort_order").notNull() }, table=>[primaryKey({columns:[table.baselineId,table.taskId]})]);
export const deliverables = sqliteTable("deliverables", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(() => projectsDb.id), taskId:text("task_id").references(() => wbsTasks.id), name:text("name").notNull(), category:text("category"), required:integer("required",{mode:"boolean"}).notNull().default(true), status:text("status").notNull().default("planned"), fileKey:text("file_key"), version:text("version"), ...audit });
export const projectIssues = sqliteTable("project_issues", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(() => projectsDb.id), taskId:text("task_id").references(() => wbsTasks.id), issueType:text("issue_type").notNull().default("issue"), title:text("title").notNull(), description:text("description"), severity:text("severity").notNull().default("medium"), status:text("status").notNull().default("open"), ownerUserId:text("owner_user_id"), dueDate:text("due_date"), ...audit });
export const projectMeetings = sqliteTable("project_meetings", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(() => projectsDb.id), title:text("title").notNull(), meetingAt:integer("meeting_at",{mode:"timestamp"}).notNull(), minutes:text("minutes"), createdBy:text("created_by").references(() => users.id), ...audit });
export const projectDocuments = sqliteTable("project_documents", { id:text("id").primaryKey(), projectId:text("project_id").notNull().references(() => projectsDb.id), taskId:text("task_id").references(() => wbsTasks.id), title:text("title").notNull(), category:text("category"), fileKey:text("file_key"), version:text("version"), status:text("status").notNull().default("draft"), createdBy:text("created_by").references(() => users.id), ...audit });
export const auditLogs = sqliteTable("audit_logs", { id:text("id").primaryKey(), companyId:text("company_id").notNull(), actorUserId:text("actor_user_id"), action:text("action").notNull(), entityType:text("entity_type").notNull(), entityId:text("entity_id").notNull(), detail:text("detail",{mode:"json"}), createdAt:integer("created_at",{mode:"timestamp"}).notNull() });

export const aiConversations = sqliteTable("ai_conversations", {
  id:text("id").primaryKey(), companyId:text("company_id").notNull(), userId:text("user_id").notNull(),
  title:text("title").notNull(), source:text("source").notNull(), contextType:text("context_type").notNull(),
  contextTitle:text("context_title").notNull(), contextItems:text("context_items",{mode:"json"}).notNull(),
  createdAt:integer("created_at",{mode:"timestamp"}).notNull(), updatedAt:integer("updated_at",{mode:"timestamp"}).notNull(),
});
export const aiMessages = sqliteTable("ai_messages", {
  id:text("id").primaryKey(), conversationId:text("conversation_id").notNull().references(()=>aiConversations.id),
  role:text("role").notNull(), content:text("content").notNull(), citations:text("citations",{mode:"json"}),
  createdAt:integer("created_at",{mode:"timestamp"}).notNull(),
});
export const userWorkState = sqliteTable("user_work_state", {
  userId:text("user_id").notNull(), stateKey:text("state_key").notNull(), value:text("value",{mode:"json"}).notNull(),
  updatedAt:integer("updated_at",{mode:"timestamp"}).notNull(),
}, table=>[primaryKey({columns:[table.userId,table.stateKey]})]);

export const workCalendars = sqliteTable("work_calendars", {
  id:text("id").primaryKey(), companyId:text("company_id").notNull().references(()=>companies.id),
  name:text("name").notNull(), timezone:text("timezone").notNull().default("Asia/Seoul"),
  workingDays:text("working_days",{mode:"json"}).notNull(), isDefault:integer("is_default",{mode:"boolean"}).notNull().default(false),
  ...audit,
});
export const calendarHolidays = sqliteTable("calendar_holidays", {
  id:text("id").primaryKey(), calendarId:text("calendar_id").notNull().references(()=>workCalendars.id,{onDelete:"cascade"}),
  holidayDate:text("holiday_date").notNull(), name:text("name").notNull(), ...audit,
}, table=>[uniqueIndex("calendar_holidays_calendar_date_uq").on(table.calendarId,table.holidayDate)]);

export const partners = sqliteTable("partners", {
  id:text("id").primaryKey(), companyId:text("company_id").notNull().references(()=>companies.id),
  code:text("code").notNull(), name:text("name").notNull(), category:text("category"), contactName:text("contact_name"),
  email:text("email"), phone:text("phone"), status:text("status").notNull().default("active"), ...audit,
}, table=>[uniqueIndex("partners_company_code_uq").on(table.companyId,table.code)]);
export const projectTypes = sqliteTable("project_types", {
  id:text("id").primaryKey(), companyId:text("company_id").notNull().references(()=>companies.id),
  code:text("code").notNull(), name:text("name").notNull(), description:text("description"), status:text("status").notNull().default("active"), ...audit,
}, table=>[uniqueIndex("project_types_company_code_uq").on(table.companyId,table.code)]);

export const partnerProfiles = sqliteTable("partner_profiles", {
  partnerId:text("partner_id").primaryKey().references(()=>partners.id,{onDelete:"cascade"}),englishName:text("english_name"),country:text("country"),industry:text("industry"),representativeName:text("representative_name"),businessRegistrationNumber:text("business_registration_number"),address:text("address"),mainPhone:text("main_phone"),extra:text("extra"),note:text("note"),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull(),
});
export const projectRoleCatalog = sqliteTable("project_role_catalog", {
  id:text("id").primaryKey(),companyId:text("company_id").notNull().references(()=>companies.id),code:text("code").notNull(),name:text("name").notNull(),groupName:text("group_name").notNull(),required:integer("required",{mode:"boolean"}).notNull().default(false),enabled:integer("enabled",{mode:"boolean"}).notNull().default(true),sortOrder:integer("sort_order").notNull().default(0),...audit,
},table=>[uniqueIndex("project_role_catalog_company_code_uq").on(table.companyId,table.code)]);
export const projectProfiles = sqliteTable("project_profiles", {projectId:text("project_id").primaryKey().references(()=>projectsDb.id,{onDelete:"cascade"}),description:text("description"),referenceCode:text("reference_code"),visibility:text("visibility").notNull().default("company"),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()});
export const projectShares = sqliteTable("project_shares", {projectId:text("project_id").notNull().references(()=>projectsDb.id,{onDelete:"cascade"}),organizationId:text("organization_id").notNull().references(()=>organizations.id),createdAt:integer("created_at",{mode:"timestamp"}).notNull()},table=>[primaryKey({columns:[table.projectId,table.organizationId]})]);
export const savedFilters = sqliteTable("saved_filters", {id:text("id").primaryKey(),companyId:text("company_id").notNull(),userId:text("user_id").notNull(),workspace:text("workspace").notNull(),name:text("name").notNull(),definition:text("definition",{mode:"json"}).notNull(),isDefault:integer("is_default",{mode:"boolean"}).notNull().default(false),...audit});
export const workspaceTabs = sqliteTable("workspace_tabs", {userId:text("user_id").notNull(),tabId:text("tab_id").notNull(),workspace:text("workspace").notNull(),title:text("title").notNull(),context:text("context",{mode:"json"}).notNull(),sortOrder:integer("sort_order").notNull().default(0),isActive:integer("is_active",{mode:"boolean"}).notNull().default(false),updatedAt:integer("updated_at",{mode:"timestamp"}).notNull()},table=>[primaryKey({columns:[table.userId,table.tabId]})]);
export const projectGateDecisions = sqliteTable("project_gate_decisions", {
  id:text("id").primaryKey(),projectId:text("project_id").notNull().references(()=>projectsDb.id),gateTaskId:text("gate_task_id").notNull().references(()=>wbsTasks.id),gateCode:text("gate_code").notNull(),decision:text("decision").notNull(),note:text("note"),decidedBy:text("decided_by").notNull().references(()=>users.id),decidedAt:integer("decided_at",{mode:"timestamp"}).notNull(),
});

export const workflowTemplates = sqliteTable("workflow_templates", {id:text("id").primaryKey(),companyId:text("company_id").notNull().references(()=>companies.id),code:text("code").notNull(),name:text("name").notNull(),applicationType:text("application_type").notNull().default("GENERAL"),description:text("description"),projectRequired:integer("project_required",{mode:"boolean"}).notNull().default(true),taskLinkMode:text("task_link_mode").notNull().default("optional"),registerCommonDocument:integer("register_common_document",{mode:"boolean"}).notNull().default(false),documentCategory:text("document_category"),status:text("status").notNull().default("active"),currentVersion:integer("current_version").notNull().default(1),...audit},table=>[uniqueIndex("workflow_templates_company_code_uq").on(table.companyId,table.code)]);
export const workflowTemplateVersions = sqliteTable("workflow_template_versions", {id:text("id").primaryKey(),templateId:text("template_id").notNull().references(()=>workflowTemplates.id),version:integer("version").notNull(),definition:text("definition",{mode:"json"}).notNull(),status:text("status").notNull().default("published"),publishedAt:integer("published_at",{mode:"timestamp"}),createdBy:text("created_by").notNull().references(()=>users.id),...audit},table=>[uniqueIndex("workflow_template_versions_template_version_uq").on(table.templateId,table.version)]);
export const workflowInstances = sqliteTable("workflow_instances", {id:text("id").primaryKey(),companyId:text("company_id").notNull().references(()=>companies.id),projectId:text("project_id").notNull().references(()=>projectsDb.id),taskId:text("task_id").references(()=>wbsTasks.id),templateId:text("template_id").notNull().references(()=>workflowTemplates.id),templateVersionId:text("template_version_id").notNull().references(()=>workflowTemplateVersions.id),workflowNumber:text("workflow_number").notNull(),title:text("title").notNull(),requestContent:text("request_content"),sourceType:text("source_type").notNull().default("GENERAL"),sourceId:text("source_id"),priority:text("priority").notNull().default("normal"),dueDate:text("due_date"),status:text("status").notNull().default("draft"),currentStepOrder:integer("current_step_order").notNull().default(0),requesterUserId:text("requester_user_id").notNull().references(()=>users.id),mainDeliverableId:text("main_deliverable_id").references(()=>deliverables.id),officialDocumentId:text("official_document_id").references(()=>projectDocuments.id),...audit},table=>[uniqueIndex("workflow_instances_company_number_uq").on(table.companyId,table.workflowNumber)]);
export const workflowInstanceSteps = sqliteTable("workflow_instance_steps", {id:text("id").primaryKey(),workflowId:text("workflow_id").notNull().references(()=>workflowInstances.id,{onDelete:"cascade"}),stepOrder:integer("step_order").notNull(),name:text("name").notNull(),actionType:text("action_type").notNull(),roleCode:text("role_code"),assignmentRule:text("assignment_rule"),dueDays:integer("due_days").notNull().default(0),commentRequired:integer("comment_required",{mode:"boolean"}).notNull().default(false),attachmentRequired:integer("attachment_required",{mode:"boolean"}).notNull().default(false),assigneeUserId:text("assignee_user_id").references(()=>users.id),status:text("status").notNull().default("waiting"),startedAt:integer("started_at",{mode:"timestamp"}),completedAt:integer("completed_at",{mode:"timestamp"}),comment:text("comment"),...audit},table=>[uniqueIndex("workflow_instance_steps_order_uq").on(table.workflowId,table.stepOrder)]);
export const workflowHistory = sqliteTable("workflow_history", {id:text("id").primaryKey(),workflowId:text("workflow_id").notNull().references(()=>workflowInstances.id,{onDelete:"cascade"}),stepId:text("step_id").references(()=>workflowInstanceSteps.id),actorUserId:text("actor_user_id").notNull().references(()=>users.id),action:text("action").notNull(),previousStatus:text("previous_status"),nextStatus:text("next_status"),comment:text("comment"),attachments:text("attachments",{mode:"json"}),createdAt:integer("created_at",{mode:"timestamp"}).notNull()});
export const designChangeRequests = sqliteTable("design_change_requests", {id:text("id").primaryKey(),companyId:text("company_id").notNull().references(()=>companies.id),projectId:text("project_id").notNull().references(()=>projectsDb.id),taskId:text("task_id").references(()=>wbsTasks.id),ecrNumber:text("ecr_number").notNull(),title:text("title").notNull(),changeTarget:text("change_target"),beforeContent:text("before_content"),afterContent:text("after_content"),reason:text("reason"),impactContent:text("impact_content"),priority:text("priority").notNull().default("normal"),requesterUserId:text("requester_user_id").notNull().references(()=>users.id),requestedAt:integer("requested_at",{mode:"timestamp"}).notNull(),workflowId:text("workflow_id").references(()=>workflowInstances.id),status:text("status").notNull().default("draft"),...audit},table=>[uniqueIndex("design_change_requests_company_number_uq").on(table.companyId,table.ecrNumber)]);
export const qualityCases = sqliteTable("quality_cases", {id:text("id").primaryKey(),companyId:text("company_id").notNull().references(()=>companies.id),projectId:text("project_id").notNull().references(()=>projectsDb.id),taskId:text("task_id").references(()=>wbsTasks.id),qualityNumber:text("quality_number").notNull(),title:text("title").notNull(),occurredOn:text("occurred_on"),issueType:text("issue_type"),severity:text("severity").notNull().default("medium"),description:text("description"),rootCause:text("root_cause"),correctiveAction:text("corrective_action"),effectivenessCheck:text("effectiveness_check"),ownerUserId:text("owner_user_id").references(()=>users.id),workflowId:text("workflow_id").references(()=>workflowInstances.id),status:text("status").notNull().default("draft"),...audit},table=>[uniqueIndex("quality_cases_company_number_uq").on(table.companyId,table.qualityNumber)]);
