/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,requireProjectAccess,resolveRequestContext} from "../../../db/request-context";
import {clearSourceParts,getSourcePrimaryPart,getSourcePartsMap,requireWorkflowPart,setSourcePrimaryPart} from "../../../services/workflow-part-service";
import {deleteDraftWorkflow,updateDraftWorkflow} from "../workflows/draft-management";
import {readSourceUpload,syncSourceAttachments} from "../workflows/source-files";
import {createWorkflowInstance,nowSeconds,seedDefaultWorkflowTemplates,workflowDb} from "../workflows/shared";

const partFields=(part:any)=>part?{partId:part.id,partNumber:part.partNumber,partName:part.name,partRevision:part.revision,partType:part.partType,partSpec:part.spec}:{};

export async function GET(request:Request){
 const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제를 불러오지 못했습니다."},{status:500})}
 const url=new URL(request.url),id=url.searchParams.get("id")||"",projectId=url.searchParams.get("projectId")||"";
 if(id){const item=await db.prepare("SELECT q.id,q.project_id AS projectId,q.task_id AS taskId,q.quality_number AS qualityNumber,q.title,q.occurred_on AS occurredOn,q.issue_type AS issueType,q.severity,q.description,q.root_cause AS rootCause,q.corrective_action AS correctiveAction,q.effectiveness_check AS effectivenessCheck,q.status,q.workflow_id AS workflowId,w.due_date AS dueDate FROM quality_cases q LEFT JOIN workflow_instances w ON w.id=q.workflow_id WHERE q.id=? AND q.company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"품질문제를 찾을 수 없습니다."},{status:404});try{await requireProjectAccess(db,context,item.projectId)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제 접근 권한이 없습니다."},{status:403})}const [attachments,part]=await Promise.all([db.prepare("SELECT id,file_name AS fileName,file_size AS fileSize,content_type AS contentType FROM workflow_source_attachments WHERE company_id=? AND source_type='QUALITY' AND source_id=? ORDER BY created_at,id").bind(context.companyId,id).all(),getSourcePrimaryPart(context.companyId,"QUALITY",id)]);return Response.json({item:{...item,...partFields(part)},part,attachments:attachments.results??[]})}
 const rows=await db.prepare(`SELECT q.id,q.quality_number AS qualityNumber,q.title,q.occurred_on AS occurredOn,q.issue_type AS issueType,q.severity,q.status,q.workflow_id AS workflowId,p.id AS projectId,p.code AS projectCode,p.name AS projectName,w.status AS workflowStatus,w.current_step_order AS currentStepOrder,w.due_date AS dueDate,cs.name AS currentStepName,cu.name AS currentAssigneeName,(SELECT COUNT(*) FROM workflow_instance_steps x WHERE x.workflow_id=w.id) AS stepCount,(SELECT string_agg(flow.name||'|'||flow.status,'~') FROM (SELECT name,status FROM workflow_instance_steps WHERE workflow_id=w.id ORDER BY step_order) flow) AS stepFlow FROM quality_cases q JOIN projects p ON p.id=q.project_id LEFT JOIN workflow_instances w ON w.id=q.workflow_id LEFT JOIN workflow_instance_steps cs ON cs.workflow_id=w.id AND cs.step_order=w.current_step_order LEFT JOIN users cu ON cu.id=cs.assignee_user_id WHERE q.company_id=? ${projectId?"AND q.project_id=?":""} ORDER BY q.updated_at DESC`).bind(context.companyId,...(projectId?[projectId]:[])).all();const items=(rows.results??[]) as any[],partsMap=await getSourcePartsMap(context.companyId,"QUALITY",items.map(item=>String(item.id)));return Response.json({items:items.map(item=>({...item,...partFields(partsMap.get(String(item.id))?.[0])}))});
}

export async function POST(request:Request){
 const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"등록 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;if(!input.projectId||!input.title?.trim())return Response.json({error:"프로젝트와 문제 제목을 입력해 주세요."},{status:400});if(!input.partId)return Response.json({error:"품질문제 대상 PART를 선택해 주세요."},{status:400});try{await requireProjectAccess(db,context,input.projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"프로젝트 접근 권한이 없습니다."},{status:403})}
 let part;try{part=await requireWorkflowPart(context.companyId,String(input.partId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"대상 PART를 확인하지 못했습니다."},{status:400})}
 const now=nowSeconds(),id=crypto.randomUUID(),seq=await db.prepare("SELECT COUNT(*) AS count FROM quality_cases WHERE company_id=?").bind(context.companyId).first<{count:number}>(),number=`QMS-${new Date().toISOString().slice(0,4)}-${String(Number(seq?.count||0)+1).padStart(4,"0")}`;await db.prepare("INSERT INTO quality_cases (id,company_id,project_id,task_id,quality_number,title,occurred_on,issue_type,severity,description,root_cause,corrective_action,effectiveness_check,owner_user_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'draft',?,?)").bind(id,context.companyId,input.projectId,input.taskId||null,number,input.title.trim(),input.occurredOn||null,input.issueType||null,input.severity||"medium",input.description||null,input.rootCause||null,input.correctiveAction||null,input.effectivenessCheck||null,input.ownerUserId||context.userId,now,now).run();
 try{await setSourcePrimaryPart(context.companyId,"QUALITY",id,part.id)}catch(reason){await db.prepare("DELETE FROM quality_cases WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({error:reason instanceof Error?reason.message:"PART 연결을 저장하지 못했습니다."},{status:500})}
 try{const workflow=await createWorkflowInstance(db,context,{projectId:input.projectId,taskId:input.taskId||undefined,templateCode:"QUALITY_ACTION",title:`[${number}] ${input.title.trim()}`,requestContent:input.description,priority:input.severity==="critical"?"urgent":"normal",dueDate:input.dueDate||undefined,sourceType:"QUALITY",sourceId:id,assignees:input.assignees,submit:Boolean(input.submit)});await db.prepare("UPDATE quality_cases SET workflow_id=?,status=?,updated_at=? WHERE id=?").bind(workflow.id,workflow.status,now,id).run();await syncSourceAttachments(db,context,{projectId:input.projectId,sourceType:"QUALITY",sourceId:id,files});return Response.json({id,qualityNumber:number,part,workflow},{status:201})}catch(reason){return Response.json({id,qualityNumber:number,error:reason instanceof Error?reason.message:"품질 Workflow를 생성하지 못했습니다."},{status:400})}
}

export async function PATCH(request:Request){
 const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"수정 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;if(!input.id)return Response.json({error:"수정할 품질문제가 필요합니다."},{status:400});if(!input.partId)return Response.json({error:"품질문제 대상 PART를 선택해 주세요."},{status:400});
 const current=await db.prepare("SELECT id,project_id AS projectId,quality_number AS qualityNumber,workflow_id AS workflowId FROM quality_cases WHERE id=? AND company_id=?").bind(input.id,context.companyId).first<any>();if(!current)return Response.json({error:"품질문제를 찾을 수 없습니다."},{status:404});try{await requireProjectAccess(db,context,current.projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제 수정 권한이 없습니다."},{status:403})}
 let part;try{part=await requireWorkflowPart(context.companyId,String(input.partId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"대상 PART를 확인하지 못했습니다."},{status:400})}await updateDraftWorkflow(db,context,current.workflowId,{title:`[${current.qualityNumber}] ${String(input.title||"").trim()}`,taskId:input.taskId||"",requestContent:input.description,priority:input.severity==="critical"?"urgent":"normal",dueDate:input.dueDate,assignees:input.assignees});
 const now=nowSeconds();await db.prepare("UPDATE quality_cases SET task_id=?,title=?,occurred_on=?,issue_type=?,severity=?,description=?,root_cause=?,corrective_action=?,effectiveness_check=?,updated_at=? WHERE id=?").bind(input.taskId||null,String(input.title||"").trim(),input.occurredOn||null,input.issueType||null,input.severity||"medium",input.description||null,input.rootCause||null,input.correctiveAction||null,input.effectivenessCheck||null,now,input.id).run();await setSourcePrimaryPart(context.companyId,"QUALITY",input.id,part.id);await syncSourceAttachments(db,context,{projectId:current.projectId,sourceType:"QUALITY",sourceId:input.id,files,removeAttachmentIds:input.removeAttachmentIds});return Response.json({ok:true,id:input.id,workflowId:current.workflowId,part});
}

export async function DELETE(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);const id=new URL(request.url).searchParams.get("id")||"",item=await db.prepare("SELECT workflow_id AS workflowId FROM quality_cases WHERE id=? AND company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"품질문제를 찾을 수 없습니다."},{status:404});const result=await deleteDraftWorkflow(db,context,item.workflowId);await clearSourceParts(context.companyId,"QUALITY",id);return Response.json(result)}catch(reason){return contextErrorResponse(reason)??Response.json({error:reason instanceof Error?reason.message:"품질문제를 삭제하지 못했습니다."},{status:400})}}
